module.exports = {
  "subject": [
    "reeg",
    "james",
    "jimmy",
    "tyra",
    "liz",
    "ton",
    "ysabel",
    "leah",
    "john madden",
    "the cake",
    "my ass",
    "your ass",
    "your mom",
    "Joe Biden",
    "sarah",
    "tom clancy",
    "pipo",
    "100,000 Ohioans",
    "the 1 out of 10 dentists that dont recommend sugarless gum",
    "the mexican villain wrestler",
    "trump",
    "dumbo's rubbery elephant schlong",
    "my favorite inflation porn artist",
    "my big tiddy anime waifu",
    "daddy",
    "our bean quean",
    "long horse",
    "the skinwalker you think is your closest friend",
    "Hasbulla",
    "a fully sentient tomato who can feel pain, but cannot scream",
    "guy fieri",
    "george bush",
    "Tom Nook",
    "your sam",
    "God",
    "Satan",
    "John Freeman",
    "jeff tutorials",
    "johoise",
    "duman",
    "a cromulent unfuckcrustable",
    "the fuckcrustables",
    "The Tainted One",
    "Mr. Imlay",
    "Mrs. Matsuyama",
    "Jeb Bush",
    "cody",
    "a sentient cum sock",
    "cool guy",
    "the spy watching your zoom meeting",
    "bilbo baggins",
    "a sentient cum sock",
    "an obama drone",
    "al qaeda",
    "melania trump",
    "michelle obama",
    "deadmau5",
    "your boss",
    "slenderman",
    "joseph smith",
    "the mormon church",
    "the pope",
    "bill burr",
    "lady gaga",
    "your neighbor",
    "your dad's best friend that you called \"uncle\" as a child",
    "your real parents",
    "colonel sanders",
    "bernie sanders",
    "the reanimated corpse of steve jobs",
    "eminem",
    "la habra 300 bowl",
    "elon musk",
    "anne frank",
    "marshall pope",
    "shigeru miyamoto",
    "your unwashed ass",
    "She Who Squirts",
    "He Who Cums",
    "Liz's cat",
    "Beemo",
    "the British",
    "bisexuals",
    "papi",
    "a bloody fucker",
    "an actual chimp",
    "shawty",
    "I",
    "Ronald Reagan",
    "Nicolas Cage",
    "Queen Elizabeth",
    "Nickelback",
    "Keanu Reeves",
    "Democrats",
    "Republicans",
    "donald johnald tronald",
    "donald john president",
    "the fall guy",
    "Disney Pixar's Cars™️ Pope Pinion IV",
    "mexican shinji ikari",
    "olm",
    "olmyra",
    "chris",
    "jed sheeran",
    "nick",
    "zach",
    "zavala",
    "ikora",
    "cayde",
    "banshee-44",
    "tess everis",
    "hawthorne",
    "calus",
    "osiris",
    "an actual nigerian prince trying to give you money",
    "donny jr",
    "mara sov",
    "xur",
    "uncle roger",
    "god",
    "your bitchy aunt",
    "your qanon uncle",
    "Q himself",
    "froggy chair",
    "socialists",
    "nazis",
    "communists",
    "John Bungie",
    "Big Oil",
    "Big Pharma",
    "ross from friends",
    "patrick star",
    "squidward",
    "chandler",
    "the shit stain in your underwear",
    "a crusty sock",
    "a cockroach",
    "seinfeld",
    "the bean quean",
    "the far left",
    "the far right",
    "centrists",
    "ben shapiro",
    "jordan peterson",
    "hillary clinton",
    "osama bin laden",
    "the mailman",
    "hamburger helper",
    "a used condom",
    "rotisserie chicken",
    "your lazy coworker",
    "Todd Howard",
    "amogus",
    "sus guy",
    "jim halpert",
    "popcat",
    "some dumb binch",
    "the CEO of Robinhood",
    "AOC",
    "ted cruz",
    "j cole",
    "elmer fudd",
    "a cum stain",
    "the inventor of Worms the video game",
    "justin timberlake",
    "the area man",
    "a rando",
    "that one friend who never interacts in discord",
    "the pogchamp guy",
    "some chud on parler",
    "an idiot who got banned from twitter",
    "mark zuckerberg's lizard offspring",
    "prince philip",
    "prince philip (in dust form)",
    "your best friend",
    "the guy",
    "robert downey jr",
    "morgan freeman",
    "a friendly neighborhood cat",
    "a birb",
    "some ducklings",
    "the person reading this",
    "abby shapiro",
    "a gamer gril",
    "a butterfly, floating peacefully",
    "Hasbulla",
    "the taliban",
    "that one guy with an eyepatch",
    "chet",
    "brad",
    "steven crowder",
    "the vitamin D council",
    "the fish oil triumvirate",
    "egg demon",
    "computer woman",
    "big elephant man",
    "that one guy that shot the ceo",
    "that one healthcare ceo",
    "obamna",
    "jesus h christ",
    "sonic the hedgehog",
    "a pube",
    "glimpmo",
    "diddy",
    "the rothschilds",
    "luigi",
    "the salami lid (it dont fit)",
    "smoog yoa",
    "wrinkled yoa",
    "Darnell Ultra",
    "Choe Biden",
    "the grink",
    "God and Jesus",
    "Mr. Beast",
    "Mr. Breast",
    "The Band 'Trapt' known for their Hit Single 'Headstrong'",
    "18 inch bruh",
    "Non-binary Peter Coin",
    "Thom Yorke",
    "Marceline the Vampire Queen",
    "Rami Malek",
    "Wednesday Addams",
    "Lupita Nyong'o",
    "Saul Goodman",
    "FKA twigs",
    "Flea",
    "Bojack Horseman",
    "Hayao Miyazaki",
    "Daenerys Targaryen",
    "Ethan Hawke",
    "Tracy Chapman",
    "Larry David",
    "Fiona Apple",
    "tony soprano",
    "meryl streep",
    "walter white",
    "beyoncé",
    "jon snow",
    "morgan freeman",
    "darth vader",
    "taylor swift",
    "homer simpson",
    "leonardo dicaprio",
    "hermione granger",
    "tom hanks",
    "katniss everdeen",
    "will smith",
    "ellen ripley",
    "brad pitt",
    "spider-man",
    "oprah winfrey",
    "indiana jones",
    "angelina jolie",
    "harry potter",
    "denzel washington",
    "princess leia",
    "robert downey jr.",
    "deadpool",
    "jennifer lawrence",
    "forrest gump",
    "samuel l. jackson",
    "wolverine",
    "emma watson",
    "iron man",
    "natalie portman",
    "jack sparrow",
    "dwayne johnson",
    "wonder woman",
    "chris evans",
    "the joker",
    "scarlett johansson",
    "james bond",
    "keanu reeves",
    "captain america",
    "johnny depp",
    "black widow",
    "george clooney",
    "batman",
    "gal gadot",
    "thor",
    "chris hemsworth",
    "superman",
    "ryan reynolds",
    "the rock",
    "margot robbie",
    "hannibal lecter",
    "anne hathaway",
    "gandalf",
    "zendaya",
    "neo",
    "charlize theron",
    "sherlock holmes",
    "idris elba",
    "lara croft",
    "jason momoa",
    "the terminator",
    "emma stone",
    "michael corleone",
    "jennifer aniston",
    "the mandalorian",
    "matt damon",
    "loki",
    "nicole kidman",
    "don vito corleone",
    "sandra bullock",
    "black panther",
    "julia roberts",
    "gollum",
    "chris pratt",
    "marty mcfly",
    "tom cruise",
    "hulk",
    "cate blanchett",
    "han solo",
    "viola davis",
    "the flash",
    "hugh jackman",
    "paul cheenis",
    "crunt",
    "John, Paul, George, and Ringo",
    "mold mario",
    "clavicular",
    "Chupapi Munyanyo",
    "chinese bill nye",
    "Mike Jones"
  ],
  "subjectirl": [
    "reeg",
    "james",
    "jimmy",
    "kacey",
    "tyra",
    "liz",
    "ton",
    "cody",
    "ysabel",
    "leah",
    "j",
    "olm",
    "adriana"
  ],
  "erW": [
    "enemy",
    "weak foe",
    "strong foe",
    "monster",
    "dragon",
    "boss",
    "sentry",
    "group",
    "pack",
    "decoy",
    "undead",
    "soldier",
    "knight",
    "cavalier",
    "archer",
    "sniper",
    "mage",
    "ordnance",
    "monarch",
    "lord",
    "demi-human",
    "outsider",
    "giant",
    "horse",
    "dog",
    "wolf",
    "rat",
    "beast",
    "bird",
    "raptor",
    "snake",
    "crab",
    "prawn",
    "octopus",
    "bug",
    "scarab",
    "slug",
    "wraith",
    "skeleton",
    "monstrosity",
    "ill-omened creature",
    "Tarnished",
    "warrior",
    "swordfighter",
    "knight",
    "samurai",
    "sorcerer",
    "cleric",
    "sage",
    "merchant",
    "teacher",
    "master",
    "friend",
    "lover",
    "old dear",
    "old codger",
    "angel",
    "fat coinpurse",
    "pauper",
    "good sort",
    "wicked sort",
    "plump sort",
    "skinny sort",
    "lovable sort",
    "pathetic sort",
    "strange sort",
    "nimble sort",
    "laggardly sort",
    "invisible sort",
    "unfathomable sort",
    "giant sort",
    "sinner",
    "thief",
    "liar",
    "dastard",
    "traitor",
    "pair",
    "trio",
    "noble",
    "aristocrat",
    "hero",
    "champion",
    "monarch",
    "lord",
    "god",
    "item",
    "necessary item",
    "precious item",
    "something",
    "something incredible",
    "treasure chest",
    "corpse",
    "coffin",
    "trap",
    "armament",
    "shield",
    "bow",
    "projectile weapon",
    "armor",
    "talisman",
    "skill",
    "sorcery",
    "incantation",
    "map",
    "material",
    "flower",
    "grass",
    "tree",
    "fruit",
    "seed",
    "mushroom",
    "tear",
    "crystal",
    "butterfly",
    "bug",
    "dung",
    "grace",
    "door",
    "key",
    "ladder",
    "lever",
    "lift",
    "spiritspring",
    "sending gate",
    "stone astrolabe",
    "Birdseye Telescope",
    "message",
    "bloodstain",
    "Erdtree",
    "Elden Ring",
    "close-quarters battle",
    "ranged battle",
    "horseback battle",
    "luring out",
    "defeating one-by-one",
    "taking on all at once",
    "rushing in",
    "stealth",
    "mimicry",
    "confusion",
    "pursuit",
    "fleeing",
    "summoning",
    "circling around",
    "jumping off",
    "dashing through",
    "brief respite",
    "Actions\t",
    "attacking",
    "jump attack",
    "running attack",
    "critical hit",
    "two-handing",
    "blocking",
    "parrying",
    "guard counter",
    "sorcery",
    "incantation",
    "skill",
    "summoning",
    "throwing",
    "healing",
    "running",
    "rolling",
    "backstepping",
    "jumping",
    "crouching",
    "target lock",
    "item crafting",
    "gesturing",
    "morning",
    "noon",
    "evening",
    "night",
    "clear sky",
    "overcast",
    "rain",
    "storm",
    "mist",
    "snow",
    "patrolling",
    "procession",
    "crowd",
    "surprise attack",
    "ambush",
    "pincer attack",
    "beating to a pulp",
    "battle",
    "reinforcements",
    "ritual",
    "explosion",
    "high spot",
    "defensible spot",
    "climbable spot",
    "bright spot",
    "dark spot",
    "open area",
    "cramped area",
    "hiding place",
    "sniping spot",
    "recon spot",
    "safety",
    "danger",
    "gorgeous view",
    "detour",
    "hidden path",
    "secret passage",
    "shortcut",
    "dead end",
    "looking away",
    "unnoticed",
    "out of stamina",
    "Places\t",
    "high road",
    "checkpoint",
    "bridge",
    "castle",
    "fort",
    "city",
    "ruins",
    "church",
    "tower",
    "camp site",
    "house",
    "cemetery",
    "underground tomb",
    "tunnel",
    "cave",
    "evergaol",
    "great tree",
    "cellar",
    "surface",
    "underground",
    "forest",
    "river",
    "lake",
    "bog",
    "mountain",
    "valley",
    "cliff",
    "waterside",
    "nest",
    "hole",
    "east",
    "west",
    "south",
    "north",
    "ahead",
    "behind",
    "left",
    "right",
    "center",
    "up",
    "down",
    "edge",
    "head",
    "stomach",
    "back",
    "arms",
    "legs",
    "rump",
    "tail",
    "core",
    "fingers",
    "physical",
    "standard",
    "striking",
    "slashing",
    "piercing",
    "fire",
    "lightning",
    "magic",
    "holy",
    "poison",
    "toxic",
    "scarlet rot",
    "blood loss",
    "frost",
    "sleep",
    "madness",
    "death",
    "life",
    "Death",
    "light",
    "dark",
    "stars",
    "fire",
    "Order",
    "chaos",
    "joy",
    "wrath",
    "suffering",
    "sadness",
    "comfort",
    "bliss",
    "misfortune",
    "good fortune",
    "bad luck",
    "hope",
    "despair",
    "victory",
    "defeat",
    "research",
    "faith",
    "abundance",
    "rot",
    "loyalty",
    "injustice",
    "secret",
    "opportunity",
    "pickle",
    "clue",
    "friendship",
    "love",
    "bravery",
    "vigor",
    "fortitude",
    "confidence",
    "distracted",
    "unguarded",
    "introspection",
    "regret",
    "resignation",
    "futility",
    "on the brink",
    "betrayal",
    "revenge",
    "destruction",
    "recklessness",
    "calmness",
    "vigilance",
    "tranquility",
    "sound",
    "tears",
    "sleep",
    "depths",
    "dregs",
    "fear",
    "sacrifice",
    "ruin",
    "good luck",
    "look carefully",
    "listen carefully",
    "think carefully",
    "well done",
    "I did it!",
    "I've failed...",
    "here!",
    "not here!",
    "don't you dare!",
    "do it!",
    "I can't take this...",
    "don't think",
    "so lonely...",
    "here again...",
    "just getting started",
    "stay calm",
    "keep moving",
    "turn back",
    "give up",
    "don't give up",
    "help me...",
    "I don't believe it...",
    "too high up",
    "I want to go home...",
    "it's like a dream...",
    "seems familiar...",
    "beautiful...",
    "you don't have the right",
    "are you ready?"
  ],
  "erP": [
    "{w} ahead",
    "Likely {w}",
    "If only I had a {w}",
    "{w}, O {w}",
    "Ahh, {w}",
    "No {w} ahead",
    "First off, {w}",
    "Didn't expect {w}...",
    "Behold, {w}!",
    "{w}",
    "{w} required ahead",
    "Seek {w}",
    "Visions of {w}...",
    "Offer {w}",
    "{w}!",
    "Be wary of {w}",
    "Still no {w}...",
    "Could this be a {w}?",
    "Praise the {w}",
    "{w}?",
    "Try {w}",
    "Why is it always {w}?",
    "Time for {w}",
    "Let there be {w}",
    "{w}..."
  ],
  "erC": [
    "and then",
    "or",
    "but",
    "therefore",
    "in short",
    "except",
    "by the way",
    "so to speak",
    "all the more",
    ","
  ],
  "things": [
    "poop",
    "in n out double double",
    "french fries",
    "a coffee",
    "hand lotion",
    "nothing",
    "alcohol",
    "hand sanitizer",
    "yeast",
    "magnets",
    "a solved rubiks cube",
    "piss from the piss drawer",
    "sad minion memes",
    "sharp objects",
    "a cat",
    "an ICE detention center",
    "a human child",
    "a bullet",
    "a rose",
    "a gun",
    "a bomb",
    "a silent fart that smells really bad",
    "a loud fart that goes unnoticed",
    "a shit you dont have to wipe",
    "a bottle of vodka",
    "a field mouse",
    "a barn cat",
    "a 1999 Toyota Corolla",
    "a semi truck full of eggs",
    "the true meaning of Christmas",
    "last year's cum sock (reborn)",
    "last year's cum sock (deceased)",
    "the source of J's power",
    "the vomit coffin",
    "the manifestation of your innermost fears",
    "the incarnation of guilt",
    "a lesser manifestation of evil",
    "the origin of cum",
    "an erect penis",
    "a flaccid penis",
    "a docile, but friendly penis",
    "an aggressive penis",
    "nothing. It's nothing. Stop fucking asking!",
    "an old pioneer survivalist strategy",
    "my left shoe",
    "a rock",
    "a boulder",
    "bees",
    "hot sauce",
    "scotch tape",
    "a breathmint",
    "a facemask",
    "a half eaten bar of chapstick",
    "some scrap metal",
    "a used condom",
    "a trashbag full of cum",
    "a rusty bicycle",
    "blood",
    "tears of the natives",
    "a crusty keyboard",
    "a half eaten burrito",
    "a mug of cold coffee",
    "a job offer",
    "nasal spray",
    "a bidet that shoots milk",
    "an old toothbrush",
    "a pen that ran out of ink",
    "tupperware full of moldy leftovers",
    "a white flag",
    "fake news",
    "the failed coup attempt perpetrated by fascist Trump supporters on the United States capitol on Jan 6, 2021",
    "Microsoft Outlook 2013",
    "lifesavers gummies",
    "a kit kat bar",
    "a newborn chimp",
    "an adult boar",
    "a dead cockroach",
    "a horny dog",
    "The Beast",
    "a succulent that you overwatered",
    "a shard of glass",
    "a honeycomb",
    "a half eaten sandwich",
    "the worst, most disgusting, carnal fantasy you've ever had",
    "a shit you definitely should have wiped",
    "a shit you wish you didn't wipe",
    "a protein bar that is well past the expiration date",
    "a pair of shit-stained underwear",
    "an asshole",
    "a really nice business card",
    "an electric fly swatter",
    "a stress ball that oozes blood",
    "a molotov cocktail",
    "an AK-47",
    "a dirty old shoe",
    "a hairball from the shower drain",
    "bad noodle",
    "a single atom",
    "a puddle of cooking oil",
    "a piss disc mid-air",
    "a t-shirt cannon",
    "a volleyball with a face",
    "in n out fries",
    "cheam creems",
    "spinch",
    "ranibow sprimkle",
    "chichen nuggest",
    "mcdonald's sprite",
    "chick fil a sauce",
    "poopy doopy wee wee haha",
    "a jar of honey",
    "a comfortable sweater",
    "an ugly, scratchy sweater",
    "a water balloon full of vinegar",
    "a can of pringles but they are all broken",
    "a dead pig",
    "dirty stripper shoes",
    "super glue",
    "a pen that ran dry ages ago",
    "an spicey meatbole",
    "a laptop with sticky keys",
    "underwear lint",
    "a sundress",
    "a funko pop of your least favorite anime character",
    "a security camera",
    "hawaiian green bean pizza",
    "my hairy ass",
    "a taint hair",
    "beast sandwich",
    "my left nut",
    "shmedium",
    "cheesy garlic bread",
    "ten gigs worth of women's butts",
    "a lime scooter",
    "a bullet casing",
    "pork juice",
    "crust",
    "a nice pen",
    "Obamunism",
    "Paul’s Cheenis",
    "good ONE",
    "Epstein’s Fortnite account",
    "goth boots",
    "coffee",
    "chia seeds",
    "some nice tea with honey",
    "shit from a butt",
    "poop from an ass",
    "a single poop from two asses",
    "piss",
    "file.data"
  ],
  "times": [
    "right now",
    "right this second :gun:",
    "in a few minutes",
    "in half an hour",
    "in an hour",
    "in a few hours",
    "tonight",
    "today",
    "tomorrow",
    "the day after tomorrow",
    "exactly 30 minutes from now",
    "in one week",
    "never",
    "at an uncertain point in the annals of history",
    "at tooth-hurty :tooth: :toothbrush:",
    "time is merely a construct",
    "TIME IS MERELY A CONSTRUCT",
    "at six, gordon!",
    "at 4:20 XDDDDDDD",
    "on 4/20 XDDDDDDD",
    "when hell freezes over",
    "when rush limbaugh died",
    "when marvel vs capcom 4 comes out",
    "when james stops bitching about sauce",
    "when final fantasy 7 remake is finished",
    "when team fortress 3 comes out",
    "when bernie sanders is elected",
    "when you fucking do something about it yourself",
    "when the imposter stops being sus",
    "at twelve bong",
    "when half life 3 comes out",
    "yesterday",
    "before you were born",
    "last tuesday",
    "when daft punk breaks up... oh",
    "whenever that franz dude got shot",
    "at dinner time",
    "when yandere simulator comes out",
    "When Bungie goes bankrupt",
    "when Papa Biden gives me the stimmy wimmy uwu",
    "when James embraces the void",
    "when the void calls me back",
    "when Duman brings me the wine",
    "whe Johoise brings me the wine",
    "when the people revolt",
    "the heat death of my anus",
    "the heat death of your anus",
    "at the beginning of the mass ejaculation event (tbd)",
    "in the middle of the mass ejaculation event",
    "at the end of the mass ejaculation event",
    "in 34 minutes and 19 seconds",
    "at around tree fiddy",
    "when ICP discovers how magnets work",
    "when your shit smells like roses",
    "when we are all vaccinated",
    "when Trump dies while choking on a clump of shit and hair",
    "in 3 days",
    "in 7 weeks",
    "in 2 months",
    "in 5 years",
    "one year from today this very minute",
    "when i discover who the FUCK invented beans",
    "when i die",
    "in a little bit...",
    "i am not sure, really",
    "eventually",
    "shortly, just wait!",
    "never..",
    "when you least expect it..",
    "when you admit you have a problem",
    "when they admit they have a problem",
    "while you are sleeping",
    "next time you fart",
    "immediately",
    "when you get off your ASS",
    "2 years from yesterday",
    "next week",
    "next sunday at 11am",
    "next wednesday at 4:19pm",
    "tomorrow morning",
    "when pigs fly",
    "the fifth of never",
    "02/30/25",
    "once in a blue moon",
    "when hell freezes over",
    "13/13/13",
    "at the crack of doom",
    "00/00/00",
    "when gta 6 comes out",
    "the twelfth of whenever",
    "at the end of time",
    "32/12/24",
    "when the cows come home",
    "99/99/99",
    "half past a monkey's ass",
    "when portal 3 gets announced",
    "eleventy-first day of smarch",
    "during the heat death of the universe",
    "29/02/23",
    "when the lakers win another championship",
    "between now and eventually",
    "when tesla makes a $25k car",
    "february 31st",
    "during the next solar eclipse",
    "25:61 pm",
    "when twitter becomes useful",
    "the day after forever",
    "when we discover aliens",
    "π o'clock",
    "the last tuesday of next week",
    "when facebook dies",
    "smarch 15th",
    "the year 20xx",
    "when netflix fixes its ui",
    "the 10th of october",
    "when half-life 3 releases",
    "the 40th hour of the day",
    "when the iphone gets usb-c",
    "the 13th month",
    "when the metaverse is cool",
    "the 32nd of december",
    "when windows stops updating",
    "the 60th minute",
    "when disney buys everything",
    "the first of octember",
    "when minecraft 2 comes out",
    "the 99th second",
    "when google+ makes a comeback",
    "the 25th hour",
    "when reddit becomes readable",
    "the day of the 53rd moon",
    "when the sun rises in the west",
    "the 0th of crunt",
    "during the next total societal collapse",
    "when the last blockbuster closes",
    "on the 100th day of quarantine",
    "when apple makes a touchscreen mac",
    "at the dawn of the third age of mankind",
    "when the cyberpunk 2077 dlc drops",
    "the 29th of february 2023",
    "when skynet goes live",
    "in the year 2525",
    "when the dollar collapses",
    "on the day the music dies",
    "when the elder scrolls 6 releases",
    "at the heat death of the universe",
    "when the beatles reunite",
    "on the 13th of octovember",
    "when twitter adds an edit button",
    "at the end of the infinity war",
    "when the last tweet is sent",
    "on the eve of robot uprising",
    "when the simpsons finally end",
    "during the next great meme war",
    "when netflix stops canceling shows",
    "on the day the internet dies",
    "when the mars colony is established",
    "at the turn of the next ice age",
    "when the last boomer posts on facebook",
    "on the 3th of junuary",
    "when the last bitcoin is mined",
    "during the next zuckerberg apology tour",
    "when the queen’s gambit season 2 drops",
    "on the 100th anniversary of sliced bread",
    "when the emoji movie wins an oscar",
    "at the start of the next pandemic",
    "when the last fax machine is destroyed",
    "on the day the aliens make contact",
    "when the last human leaves earth",
    "at the peak of the next crypto crash",
    "when the matrix glitches",
    "on the 404th day of the year",
    "when the first ai president is elected",
    "during the next great social media migration",
    "when the last dvd player stops working",
    "on the day the robots unionize",
    "when the last magazine is printed",
    "at the moment time travel is invented",
    "when the last vhs tape degrades",
    "on the 99th anniversary of the ipod",
    "when the first meme becomes sentient",
    "at the exact second nostalgia dies",
    "when asses learn to wipe themselves",
    "when you forgive yourself",
    "when the clock strokes its shit its got lotion on its shit it's horny as fuuuuck",
    "lunch time",
    "when the penne explodes"
  ],
  "locations": [
    "the Grand Canyon",
    "a sex dungeon",
    "my sex dungeon",
    "the moon",
    "the Epstein island",
    "a gulag",
    "Big Ben",
    "Ireland",
    "the bottom of the Atlantic Ocean",
    "Ohio",
    "Deep Stone Crypt",
    "a Garfield comic",
    "Mystery Flesh Pit National Park, Texas",
    "Hell",
    "Heaven",
    "Purgatory",
    "Limbo (The outer border of Hell, not the game)",
    "Limbo (The game, not the outer border of Hell)",
    "de_dust2",
    "2Fort",
    "gm_construct",
    "Taco Bell:tm:",
    "Mcdonalds:tm:",
    "a strip club",
    "my basement",
    "a basement",
    "a haunted house",
    "my arms",
    "my arms, bridal style",
    "the Piss Drawer:tm:",
    "Northern Undead Asylum",
    "Anor Londo",
    "Firelink Shrine",
    "the cum sock",
    "Lavender Town",
    "Yharnam",
    "Blood Gulch",
    "Brazil",
    "the alley behind Tesco",
    "Gondor",
    "the New California Republic",
    "the New California Republic",
    "Kekistan",
    "Shangri-La",
    "Wakanda",
    "Duckburg",
    "Mos Eisley",
    "Castle Rock",
    "City 17",
    "Night City",
    "Raccoon City",
    "Skyrim",
    "Jame's bedroom",
    "the toilet",
    "the cum hamper",
    "the piss drawer",
    "my rectum",
    "your ear",
    "6 feet underground",
    "under AOC's feet",
    "Atlantis",
    "among the trees",
    "North Korea",
    "screaming from within the vomit coffin",
    "within Shaq's intercranial space",
    "flailing endlessly through innumerable, spontaneous cycles of death and rebirth",
    "within the fibers of Mario's mustache",
    "the bathroom at work",
    "the trough urinal at the baseball stadium",
    "ronald reagan's grave",
    "wakanda",
    "hogwarts",
    "times square",
    "the shire",
    "area 51",
    "raccoon city",
    "mount olympus",
    "silent hill",
    "the white house",
    "middle-earth",
    "narnia",
    "area 52",
    "the batcave",
    "atlantis",
    "disneyland",
    "springfield",
    "the death star",
    "gotham city",
    "las vegas",
    "tatooine",
    "alcatraz",
    "the upside down",
    "yellowstone",
    "mordor",
    "the grand canyon",
    "stars hollow",
    "the bermuda triangle",
    "rivendell",
    "area 51",
    "the hollywood sign",
    "themyscira",
    "pandora",
    "the sahara desert",
    "twin peaks",
    "metropolis",
    "neverland",
    "area 52",
    "the great pyramid",
    "the milky way",
    "king's landing",
    "area 53",
    "the eiffel tower",
    "the twilight zone",
    "area 54",
    "the mariana trench",
    "area 55",
    "the lost city of z",
    "area 56",
    "the x-files basement",
    "area 57",
    "night city",
    "the overlook hotel",
    "machu picchu",
    "rapture",
    "the great wall of china",
    "black mesa",
    "mount doom",
    "the colosseum",
    "arkham city",
    "the himalayas",
    "night vale",
    "the sydney opera house",
    "city 17",
    "the amazon rainforest",
    "twin peaks",
    "the golden gate bridge",
    "silent hill",
    "the statue of liberty",
    "derry",
    "the niagara falls",
    "lothlórien",
    "the taj mahal",
    "raccoon city",
    "the leaning tower of pisa",
    "the island (lost)",
    "the great barrier reef",
    "mos eisley",
    "the forbidden city",
    "silent hill",
    "mount rushmore",
    "the backrooms",
    "the eiffel tower",
    "jurassic park",
    "the grand budapest hotel",
    "the bermuda triangle",
    "the hollywood sign",
    "the misty mountains",
    "the white house",
    "the x-files basement",
    "the mariana trench",
    "the lost city of atlantis",
    "the shining's overlook hotel",
    "the great pyramid of giza",
    "the milky way",
    "the twilight zone",
    "the sahara desert",
    "the batcave",
    "the death star",
    "the citadel (half-life)",
    "the elder scrolls' tamriel",
    "paul cheenis' cheenis shack",
    "choose any 3 of your holes",
    "my lair",
    "my taint",
    "Israel",
    "Cedar Rapids",
    "toilet"
  ],
  "reasons": [
    "said the earth is flat",
    "has a girthy balloon shlong",
    "h",
    "stinky",
    "said chemtrails are turning people gay",
    "Epstein didn't kill himself",
    "be shoppin",
    "is coming to town",
    "is watching you",
    "happens for a reason",
    "doesn't care about black people",
    "benefits the military-industrial complex",
    "has never had a dream",
    "isn't real",
    "thinks 2pac is still alive",
    "'s anus is bleeding",
    "has been farting alone in flaccid chat for 6 hours",
    "said it in secret chat",
    "ate the burger king foot lettuce",
    "is going to kick your ass, and i'm going to help him",
    "is a lizard",
    "forgot the question",
    "is an alcoholic",
    "wills it to be so.",
    "profited off the Iraq war",
    "opinions only get worse",
    "says GHIF",
    "is COOOOOOOOOOOMING",
    "is a :clown:",
    "going to lose subscriber",
    "told malarkey",
    ", dey suffer",
    "hates white pipo",
    "is SO BEEFY!!",
    "killed hooters",
    "dont trust you :sob:",
    "is in love with the coco :weary:",
    "didn't hit that MF LIKE AND SUBSCRIBE BUTTON",
    "said poopie is funny",
    "said UH OH, stinky",
    "rotted",
    "is a figment of your imagination",
    "is once again asking you to shut the fuck up",
    "is ignoring your pings",
    "SUKA BLYAT",
    "is a TABLE",
    "hardly knows her!",
    "can't read",
    "shidded",
    "has a smol pebis",
    "is cooming",
    "has abandoned us",
    "calls it oven when you of in the cold food of out hot eat the food",
    "has a salty six inch that isn't big enough for the both of us",
    "is the king of being wrong",
    "decreed it",
    "does not rove da rord",
    "never reveals her age",
    "can has cheesburger",
    "once said 7 eleven hot dogs aren't that bad",
    "thinks taco bell is mexican food",
    "thinks del taco is better than taco bell",
    "thinks ketchup doesn't belong on eggs",
    "bought another iPhone",
    "is the reason rotisserie chicken from albertsons is so cheap...",
    "says italian food is better than any other food",
    "has a perfect fat pussy",
    "went to five or six stores instead of just one",
    "is afraid to leave his stoop",
    "is a republican",
    "joined a pyramid scheme",
    "shouldn't be allowed to vote",
    "said squirt is pee",
    "`shidded and farded and cummed`",
    "INVENTED BEANS",
    "is stored in the ass",
    "is stored in the balls",
    "deleted it because they did not like it",
    "is stored in the soul",
    "never returned backdoor sluts 4 to blockbuster :flushed:",
    "because la habra 300 bowl is",
    "doesn't wash their ass",
    "is a registered sex offender in 38 states",
    "leg so hot it fry an eg",
    "slings a fat hog",
    "peed in the sink",
    "has a worryingly skinny pussy",
    "has coronavirus",
    "went tits up in the stock market",
    "was left off bad n boujee",
    "got its lime :beers:",
    "needs kammies",
    "is a masochist",
    "has gone mental, absolutely bonkers",
    "never really loved you anyway",
    "is secretly an alt-right youtuber with a cartoon animal avatar in a suit",
    "wants to wear your skin",
    "smells like gun-girl's undies",
    "is locked in an ICE internment center",
    "doesn't care about black people",
    "need drinky",
    "is a fuckcrustable",
    "is a massive fucktardian cunt waffle of epic proportions",
    "got a tutorial from jeff",
    "has dementia",
    "forgot to",
    "has died",
    "worships satan",
    "has 3 nipples",
    "smells like shit",
    "drank redbull and didn't get wings",
    "really needs a sorking",
    "cums first",
    "wasn't invited to the Roman orgy",
    "is off his rocker, innit?",
    "has nipple piercings",
    "creamed in the trash",
    "do kinda be vibin tho",
    "is tokin n strokin, bruv",
    "did black face 10 years ago",
    "smokes cigarettes without the filters",
    "confused ham for string beans",
    "was made deaf by space",
    "ate bad noodle",
    "thinks green beans belong on pizza",
    "sniffs cocks",
    "pood and pidded",
    "came in the shower",
    "farted at work",
    "hates minorities",
    "is too beautiful for this earth",
    "is a binch",
    "sucks",
    "tried to fart but accidentally shit",
    "once slapped a nun",
    "is a ghost",
    "prefers boned wings",
    "is a degenerate",
    "is wanted by INTERPOL",
    "shits standing up",
    "is an undercover FBI agent",
    "doesnt wipe",
    "hides snacks in their foreskin",
    "has ashy skin",
    "has no teeth",
    "invented green bean pizza",
    "draws furries for a living",
    "yiffs in their free time",
    "is secretly a chud",
    "loves the pungent copypasta",
    "types with two fingers",
    "goes to sink-pissers anonymous",
    "is addicted to crack",
    "is addicted to their own farts",
    "is a nice person, actually",
    "eats with their mouth open",
    "microwaves cat food in the office",
    "thinks the earth is flat",
    "is an antivaxxer",
    "is in a coma. wake up please!",
    "is illegal",
    "only wipes if people are watching",
    "is the reason there is always piss on the toilet seat",
    "clogged the toilet",
    "is the zodiac killer",
    "wishes they could feel pain",
    "has diarrhea",
    "is gassy",
    "is a bigg dummy",
    "has a sex tape",
    "is ben shapiro's wife",
    "sucks eggs",
    "walks too slowly in public",
    "is Q",
    "crop dusted some old guy reading the paper",
    "shouldn't have trusted that fart",
    "flew to cancun",
    "is le epic redditor extraordinaire mlady",
    "eats kool aid pickles",
    "denies the holocaust",
    "is the imposter",
    "is lookin pretty sus ngl",
    "is amogus",
    "has night vision",
    "isn't allowed to fart",
    "will NOT be coming back to this establishment",
    "spilled the cum jar",
    "cannot be arsed to care",
    "is a serial killer",
    "is stinky",
    "is your real dad",
    "is cursed to edge for eternity",
    "is blasting rope",
    "just blasted rope",
    "shidded they pant and underwear also",
    "cried when henry kissinger died",
    "love scat porn",
    "is secretly a Rothschild",
    "is freaky, they're horny",
    "lost the salami lid",
    "isn't here",
    "I KNOW they ate a cheese",
    "is off the drankies",
    "has a Brian Griffin tattoo",
    "something chinese happened",
    "needs to spread their spore",
    "got caught looksmaxxing",
    "they fucking love peanut butter",
    "they fucking love science! 🤪",
    "of WOKE",
    "allah willed it to be so",
    "i'm spooky",
    "HEEEELP!! HELP MEE!!!! THIS IS NOT A JOKE HELP!!!!!",
    "I’m freaky!",
    "I’m freaky! I'm horny!",
    "is shit thumping and pisspilling",
    "losing subscriber!",
    "sun downing in the club"
  ],
  "ballsizes": [
    "large",
    "small",
    "medium",
    "puny",
    "gigantic",
    "average",
    "incongruous",
    "nice :thumbsup:",
    ":b:ig",
    "immense",
    "voluptuous",
    "h",
    "bigger than I'd like :/",
    "smaller than I'd like :/",
    "vast",
    "globular",
    "eternal",
    "*just right*",
    "normal",
    "¡Sabado Gigante!",
    "narrow",
    "wide",
    "petite",
    "insignificant",
    "short",
    "0.127 mm",
    ":ok:",
    "smallish",
    "XXL",
    "XXS",
    "big-boned",
    "king size",
    "FAT",
    "mediocre",
    "unexceptional",
    "immeasurable",
    "trivial",
    "intermediate",
    "passable",
    "regular",
    "tainted",
    "common",
    "12 inches",
    "1 foot",
    "5 & 1/2 centimeters",
    "futuristic",
    "macho",
    "4 yards",
    "2 meters",
    ":fire::100::fire::100::fire::100:",
    "thicc",
    "microscopic",
    "gargantuan",
    ":flushed:",
    "assertive",
    "reptilian",
    "ghastly",
    "delightful",
    "debonair",
    "homely",
    "nonexistent",
    "left: 15cm, right: 1cm",
    "1mm",
    "1 in.",
    "3cm",
    "about that of a golf ball",
    "Epstein didn't kill himself",
    "too big to handle",
    "just right",
    "ordinary",
    "unwieldy",
    "embarrassing",
    "cubic",
    "shriveled",
    "that of a BEAN",
    "six of one, half dozen of the other",
    "an acre",
    "US Men's 11",
    "UK Women's 7 & 1/2",
    "a lima bean",
    "unusual",
    "gamer sized :video_game:",
    "amassed",
    "in South Carolina until 10/12",
    "husky",
    "big and tall",
    "fine",
    "sizeable",
    "beach ball",
    ":chart_with_upwards_trend:",
    ":chart_with_downwards_trend:",
    "boomer-sized",
    "minute",
    "old-fashioned",
    "frail",
    "nutty",
    "broad",
    "crooked",
    "euclidean",
    "obtuse",
    "portable",
    "stubby",
    "insufficient",
    "plump",
    "corn-fed",
    "flabby",
    "opulent",
    "liberal",
    "confusing",
    "questionable",
    "lacking self-confidence",
    "uncertain",
    "meager",
    "lacking quality",
    "free",
    "enslaved",
    "distinguished",
    "vegan",
    "poignant",
    "special 🙂",
    "enticing <:bites_lip:813835068904701972>",
    "2gb",
    "freaky",
    "creepy",
    "wet",
    "the size of the smallest in n out yellow chili youve ever seen",
    "wimpy",
    "potato-like",
    "confused"
  ],
  "allEmoji": [
    "🅰️",
    "🅱️",
    "🅾️",
    "🅿️",
    "🆎",
    "🆑",
    "🆒",
    "🆓",
    "🆔",
    "🆕",
    "🆖",
    "🆗",
    "🆘",
    "🆙",
    "🌂",
    "🌃",
    "🌄",
    "🌅",
    "🌆",
    "🌇",
    "🌈",
    "🌉",
    "🌊",
    "🌋",
    "🌌",
    "🌍",
    "🌐",
    "🌑",
    "🌒",
    "🌕",
    "🌙",
    "🌚",
    "🌛",
    "🌜",
    "🌝",
    "🌞",
    "🌟",
    "🌠",
    "🌡️",
    "🌤️",
    "🌥️",
    "🌦️",
    "🌧️",
    "🌨️",
    "🌩️",
    "🌪️",
    "🌫️",
    "🌬️",
    "🌭",
    "🌮",
    "🌯",
    "🌰",
    "🌱",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🌶️",
    "🌷",
    "🌸",
    "🌹",
    "🌺",
    "🌻",
    "🌼",
    "🌽",
    "🌾",
    "🌿",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🍄",
    "🍅",
    "🍆",
    "🍇",
    "🍈",
    "🍉",
    "🍊",
    "🍋",
    "🍌",
    "🍍",
    "🍎",
    "🍏",
    "🍐",
    "🍑",
    "🍒",
    "🍓",
    "🍔",
    "🍕",
    "🍖",
    "🍗",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍞",
    "🍟",
    "🍠",
    "🍡",
    "🍢",
    "🍣",
    "🍤",
    "🍥",
    "🍦",
    "🍧",
    "🍨",
    "🍩",
    "🍪",
    "🍫",
    "🍬",
    "🍭",
    "🍮",
    "🍯",
    "🍰",
    "🍱",
    "🍲",
    "🍳",
    "🍴",
    "🍵",
    "🍶",
    "🍷",
    "🍸",
    "🍹",
    "🍺",
    "🍻",
    "🍼",
    "🍽️",
    "🍾",
    "🍿",
    "🎀",
    "🎁",
    "🎂",
    "🎃",
    "🎄",
    "🎅",
    "🎆",
    "🎇",
    "🎈",
    "🎉",
    "🎊",
    "🎋",
    "🎌",
    "🎍",
    "🎎",
    "🎏",
    "🎐",
    "🎑",
    "🎒",
    "🎓",
    "🎖️",
    "🎗️",
    "🎙️",
    "🎚️",
    "🎛️",
    "🎞️",
    "🎟️",
    "🎠",
    "🎡",
    "🎢",
    "🎣",
    "🎤",
    "🎥",
    "🎦",
    "🎧",
    "🎨",
    "🎩",
    "🎪",
    "🎫",
    "🎬",
    "🎭",
    "🎮",
    "🎯",
    "🎰",
    "🎱",
    "🎲",
    "🎳",
    "🎴",
    "🎵",
    "🎶",
    "🎷",
    "🎸",
    "🎹",
    "🎺",
    "🎻",
    "🎼",
    "🎽",
    "🎾",
    "🎿",
    "🏀",
    "🏁",
    "🏌️",
    "🏍️",
    "🏎️",
    "🏏",
    "🏐",
    "🏑",
    "🏒",
    "🏓",
    "🏔️",
    "🏕️",
    "🏖️",
    "🏗️",
    "🏘️",
    "🏙️",
    "🏚️",
    "🏛️",
    "🏜️",
    "🏝️",
    "🏞️",
    "🏟️",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏧",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏮",
    "🏯",
    "🏰",
    "🏳️‍🌈",
    "🏴",
    "🏵️",
    "🏷️",
    "🏸",
    "🏹",
    "🏺",
    "🐀",
    "🐈",
    "🐉",
    "🐊",
    "🐋",
    "🐌",
    "🐍",
    "🐎",
    "🐏",
    "🐐",
    "🐑",
    "🐒",
    "🐓",
    "🐔",
    "🐕‍🦺",
    "🐕",
    "🐖",
    "🐗",
    "🐘",
    "🐙",
    "🐚",
    "🐛",
    "🐜",
    "🐝",
    "🐞",
    "🐟",
    "🐠",
    "🐡",
    "🐢",
    "🐣",
    "🐤",
    "🐥",
    "🐦",
    "🐧",
    "🐨",
    "🐩",
    "🐪",
    "🐫",
    "🐬",
    "🐭",
    "🐮",
    "🐯",
    "🐰",
    "🐱",
    "🐲",
    "🐳",
    "🐴",
    "🐵",
    "🐶",
    "🐷",
    "🐸",
    "🐹",
    "🐺",
    "🐻",
    "🐼",
    "🐽",
    "🐾",
    "🐿️",
    "👀",
    "👁‍🗨",
    "👁️",
    "👃",
    "👄",
    "👅",
    "👆",
    "👈",
    "👋",
    "👌",
    "👍",
    "👏",
    "👐",
    "👑",
    "👒",
    "👓",
    "👔",
    "👕",
    "👖",
    "👗",
    "👘",
    "👙",
    "👚",
    "👛",
    "👜",
    "👝",
    "👞",
    "👟",
    "👠",
    "👡",
    "👢",
    "👣",
    "👤",
    "👥",
    "👹",
    "👺",
    "👻",
    "👼",
    "👽",
    "👾",
    "👿",
    "💀",
    "💃",
    "💄",
    "💅",
    "💆",
    "💇‍♀️",
    "💇‍♂️",
    "💇",
    "💈",
    "💉",
    "💊",
    "💋",
    "💌",
    "💍",
    "💎",
    "💏",
    "💐",
    "💑",
    "💒",
    "💓",
    "💔",
    "💕",
    "💖",
    "💗",
    "💘",
    "💙",
    "💚",
    "💛",
    "💜",
    "💝",
    "💞",
    "💟",
    "💠",
    "💡",
    "💢",
    "💣",
    "💤",
    "💥",
    "💦",
    "💧",
    "💨",
    "💩",
    "💪",
    "💫",
    "💬",
    "💭",
    "💮",
    "💯",
    "💰",
    "💱",
    "💲",
    "💳",
    "💴",
    "💵",
    "💶",
    "💷",
    "💸",
    "💹",
    "💺",
    "💻",
    "💼",
    "💽",
    "💾",
    "💿",
    "📀",
    "📁",
    "📂",
    "📃",
    "📄",
    "📅",
    "📆",
    "📇",
    "📈",
    "📉",
    "📊",
    "📋",
    "📌",
    "📍",
    "📎",
    "📏",
    "📐",
    "📑",
    "📒",
    "📓",
    "📔",
    "📕",
    "📖",
    "📗",
    "📘",
    "📙",
    "📚",
    "📛",
    "📜",
    "📝",
    "📞",
    "📟",
    "📠",
    "📡",
    "📢",
    "📣",
    "📤",
    "📥",
    "📦",
    "📧",
    "📨",
    "📩",
    "📪",
    "📫",
    "📬",
    "📭",
    "📮",
    "📯",
    "📰",
    "📱",
    "📲",
    "📳",
    "📴",
    "📵",
    "📶",
    "📷",
    "📸",
    "📹",
    "📺",
    "📻",
    "📼",
    "📽️",
    "📿",
    "🔀",
    "🔁",
    "🔂",
    "🔃",
    "🔄",
    "🔅",
    "🔆",
    "🔇",
    "🔈",
    "🔉",
    "🔊",
    "🔋",
    "🔌",
    "🔍",
    "🔎",
    "🔏",
    "🔐",
    "🔑",
    "🔒",
    "🔓",
    "🔔",
    "🔕",
    "🔖",
    "🔗",
    "🔘",
    "🔙",
    "🔚",
    "🔛",
    "🔜",
    "🔝",
    "🔞",
    "🔟",
    "🔠",
    "🔡",
    "🔢",
    "🔣",
    "🔤",
    "🔥",
    "🔦",
    "🔧",
    "🔨",
    "🔩",
    "🔪",
    "🔫",
    "🔬",
    "🔭",
    "🔮",
    "🔯",
    "🔰",
    "🔱",
    "🔲",
    "🔳",
    "🔴",
    "🔵",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "🔼",
    "🔽",
    "🕉️",
    "🕊️",
    "🕋",
    "🕌",
    "🕍",
    "🕎",
    "🕐",
    "🕯️",
    "🕰️",
    "🕵️‍♀️",
    "🕵️‍♂️",
    "🕵️",
    "🕶️",
    "🕷️",
    "🕸️",
    "🕺",
    "🖇️",
    "🖐️",
    "🖤",
    "🖥️",
    "🖨️",
    "🖱️",
    "🖲️",
    "🖼️",
    "🗂️",
    "🗃️",
    "🗄️",
    "🗑️",
    "🗒️",
    "🗓️",
    "🗜️",
    "🗝️",
    "🗞️",
    "🗡️",
    "🗣️",
    "🗨️",
    "🗯️",
    "🗳️",
    "🗺️",
    "🗻",
    "🗼",
    "🗽",
    "🗾",
    "🗿",
    "😀",
    "😁",
    "😂",
    "😃",
    "😄",
    "😅",
    "😆",
    "😇",
    "😈",
    "😉",
    "😊",
    "😋",
    "😌",
    "😍",
    "😎",
    "😏",
    "😐",
    "😑",
    "😒",
    "😓",
    "😔",
    "😕",
    "😖",
    "😗",
    "😘",
    "😙",
    "😚",
    "😛",
    "😜",
    "😝",
    "😞",
    "😟",
    "😠",
    "😡",
    "😢",
    "😣",
    "😤",
    "😥",
    "😦",
    "😧",
    "😨",
    "😩",
    "😪",
    "😫",
    "😬",
    "😭",
    "😮",
    "😯",
    "😰",
    "😱",
    "😲",
    "😳",
    "😴",
    "😵",
    "😶",
    "😷",
    "😸",
    "😹",
    "😺",
    "😻",
    "😼",
    "😽",
    "😾",
    "😿",
    "🙀",
    "🙁",
    "🙂",
    "🙃",
    "🙄",
    "🙅‍♀️",
    "🙅‍♂️",
    "🙅",
    "🙆‍♀️",
    "🙆‍♂️",
    "🙆",
    "🙇‍♀️",
    "🙇‍♂️",
    "🙇",
    "🙈",
    "🙉",
    "🙊",
    "🙋‍♀️",
    "🙋‍♂️",
    "🙋",
    "🙌",
    "🙍‍♀️",
    "🙍‍♂️",
    "🙍",
    "🙎‍♀️",
    "🙎‍♂️",
    "🙎",
    "🙏",
    "🚀",
    "🚁",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚋",
    "🚌",
    "🚍",
    "🚎",
    "🚏",
    "🚐",
    "🚑",
    "🚒",
    "🚓",
    "🚔",
    "🚕",
    "🚖",
    "🚗",
    "🚘",
    "🚙",
    "🚚",
    "🚛",
    "🚜",
    "🚝",
    "🚞",
    "🚟",
    "🚠",
    "🚡",
    "🚢",
    "🚣",
    "🚤",
    "🚥",
    "🚦",
    "🚧",
    "🚨",
    "🚩",
    "🚪",
    "🚫",
    "🚬",
    "🚭",
    "🚮",
    "🚯",
    "🚰",
    "🚱",
    "🚲",
    "🚳",
    "🚵‍♀️",
    "🚵‍♂️",
    "🚵",
    "🚶‍♀️",
    "🚶‍♂️",
    "🚶",
    "🚷",
    "🚸",
    "🚹",
    "🚺",
    "🚻",
    "🚼",
    "🚽",
    "🚾",
    "🚿",
    "🛀",
    "🛁",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "🛌",
    "🛍️",
    "🛎️",
    "🛏️",
    "🛐",
    "🛑",
    "🛒",
    "🛕",
    "🛠️",
    "🛡️",
    "🛢️",
    "🛣️",
    "🛤️",
    "🛥️",
    "🛩️",
    "🛫",
    "🛬",
    "🛰️",
    "🛳️",
    "🛴",
    "🛵",
    "🛶",
    "🛷",
    "🛸",
    "🛹",
    "🛺",
    "🛻",
    "🛼",
    "🟠",
    "🟡",
    "🟢",
    "🟣",
    "🟤",
    "🟥",
    "🟦",
    "🟧",
    "🟨",
    "🟩",
    "🟪",
    "🟫",
    "🤍",
    "🤏",
    "🤐",
    "🤑",
    "🤒",
    "🤓",
    "🤔",
    "🤕",
    "🤖",
    "🤗",
    "🤘",
    "🤙",
    "🤚",
    "🤛",
    "🤝",
    "🤞",
    "🤟",
    "🤠",
    "🤡",
    "🤢",
    "🤣",
    "🤤",
    "🤥",
    "🤦‍♀️",
    "🤦‍♂️",
    "🤦",
    "🤧",
    "🤨",
    "🤩",
    "🤪",
    "🤫",
    "🤬",
    "🤭",
    "🤮",
    "🤯",
    "🤿",
    "🥀",
    "🥁",
    "🥂",
    "🥃",
    "🥄",
    "🥅",
    "🥇",
    "🥈",
    "🥉",
    "🥊",
    "🥋",
    "🥌",
    "🥍",
    "🥎",
    "🥏",
    "🥐",
    "🥑",
    "🥒",
    "🥓",
    "🥔",
    "🥕",
    "🥖",
    "🥗",
    "🥘",
    "🥙",
    "🥚",
    "🥛",
    "🥜",
    "🥝",
    "🥞",
    "🥟",
    "🥠",
    "🥡",
    "🥢",
    "🥣",
    "🥤",
    "🥥",
    "🥦",
    "🥧",
    "🥨",
    "🥩",
    "🥪",
    "🥫",
    "🥬",
    "🥭",
    "🥮",
    "🥯",
    "🥰",
    "🥱",
    "🥲",
    "🥳",
    "🥴",
    "🥵",
    "🥶",
    "🧑",
    "🧕",
    "🧚",
    "🧜‍♀️",
    "🧝‍♀️",
    "🧝‍♂️",
    "🧝",
    "🧞‍♀️",
    "🧞‍♂️",
    "🧞",
    "🧟‍♀️",
    "🧠",
    "🧡",
    "🧢",
    "🧣",
    "🧤",
    "🧥",
    "🧦",
    "🧧",
    "🧨",
    "🧩",
    "🧪",
    "🧫",
    "🧬",
    "🧭",
    "🧮",
    "🧯",
    "🧰",
    "🧱",
    "🧲",
    "🧳",
    "🧴",
    "🧵",
    "🧶",
    "🧷",
    "🧸",
    "🧹",
    "🧺",
    "🧻",
    "🧼",
    "🧽",
    "🧾",
    "🧿",
    "🩰",
    "🩱",
    "🩲",
    "🩳",
    "🩴",
    "🩸",
    "🩹",
    "🩺",
    "🪀",
    "🪁",
    "🪂",
    "🪐",
    "🪑",
    "🪒",
    "🪓",
    "🪔",
    "‼️",
    "⁉️",
    "™️",
    "ℹ️",
    "↔️",
    "⏰",
    "⏱️",
    "⏲️",
    "⏳",
    "☀️",
    "☁️",
    "☂️",
    "☃️",
    "☄️",
    "☎️",
    "☑️",
    "☔️",
    "☕️",
    "☘️",
    "☝️",
    "☠️",
    "☢️",
    "☣️",
    "☦️",
    "☪️",
    "☮️",
    "☯️",
    "☸️",
    "☹️",
    "☺️",
    "♀️",
    "♂️",
    "♟️",
    "♠️",
    "♣️",
    "♥️",
    "♦️",
    "♨️",
    "♻️",
    "♾",
    "♿️",
    "⚒️",
    "⚓️",
    "⚔️",
    "⚕️",
    "⚖️",
    "⚗️",
    "⚙️",
    "⚛️",
    "⚜️",
    "⚠️",
    "⚡️",
    "⚧️",
    "⚪️",
    "⚫️",
    "⚰️",
    "⚱️",
    "⚽️",
    "⚾️",
    "⛄️",
    "⛅️",
    "⛈️",
    "⛏️",
    "⛑️",
    "⛓️",
    "⛔️",
    "⛰️",
    "⛱️",
    "⛳️",
    "⛴️",
    "⛷️",
    "⛺️",
    "✂️",
    "✅",
    "✈️",
    "✉️",
    "✊",
    "✋",
    "✌️",
    "✍️",
    "✏️",
    "✒️",
    "✔️",
    "✖️",
    "✝️",
    "✡️",
    "✨",
    "✳️",
    "✴️",
    "❄️",
    "❇️",
    "❌",
    "❎",
    "❓",
    "❗️",
    "❣️",
    "❤️",
    "➕",
    "➖",
    "➗",
    "➡️",
    "➰",
    "➿",
    "⤴️",
    "⤵️",
    "*⃣",
    "⬅️",
    "⬆️",
    "⬇️",
    "⬛️",
    "⬜️",
    "⭕️"
  ],
  "wtf": "What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.",
  "cummies": "Just me and my :two_hearts:daddy:two_hearts:, hanging out I got pretty hungry:eggplant: so I started to pout :disappointed: He asked if I was down :arrow_down:for something yummy :heart_eyes::eggplant: and I asked what and he said he'd give me his :sweat_drops:cummies!:sweat_drops: Yeah! Yeah!:two_hearts::sweat_drops: I drink them!:sweat_drops: I slurp them!:sweat_drops: I swallow them whole:sweat_drops: :heart_eyes: It makes :cupid:daddy:cupid: :blush:happy:blush: so it's my only goal... :two_hearts::sweat_drops::tired_face:Harder daddy! Harder daddy! :tired_face::sweat_drops::two_hearts: 1 cummy:sweat_drops:, 2 cummy:sweat_drops::sweat_drops:, 3 cummy:sweat_drops::sweat_drops::sweat_drops:, 4:sweat_drops::sweat_drops::sweat_drops::sweat_drops: I'm :cupid:daddy's:cupid: :crown:princess :crown:but I'm also a whore! :heart_decoration: He makes me feel squishy:heartpulse:!He makes me feel good:purple_heart:! :cupid::cupid::cupid:He makes me feel everything a little kitten should!~ :cupid::cupid::cupid: :crown::sweat_drops::cupid:Wa-What!:cupid::sweat_drops::crown:"
};