module.exports = {
  "people": [
    "reeg",
    "james",
    "jimmy",
    "tyra",
    "liz",
    "ton",
    "ysabel",
    "leah",
    "john madden",
    "the cake",
    "my ass",
    "your ass",
    "your mom",
    "Joe Biden",
    "sarah",
    "tom clancy",
    "pipo",
    "100,000 Ohioans",
    "the 1 out of 10 dentists that dont recommend sugarless gum",
    "the mexican villain wrestler",
    "trump",
    "dumbo's rubbery elephant schlong",
    "my favorite inflation porn artist",
    "my big tiddy anime waifu",
    "daddy",
    "our bean quean",
    "long horse",
    "Hasbulla",
    "a fully sentient tomato who can feel pain, but cannot scream",
    "guy fieri",
    "george bush",
    "Tom Nook",
    "your sam",
    "God",
    "Satan",
    "John Freeman",
    "jeff tutorials",
    "johoise",
    "duman",
    "a cromulent unfuckcrustable",
    "the fuckcrustables",
    "The Tainted One",
    "Mr. Imlay",
    "Mrs. Matsuyama",
    "Jeb Bush",
    "cody",
    "a sentient cum sock",
    "cool guy",
    "the spy watching your zoom meeting",
    "bilbo baggins",
    "a sentient cum sock",
    "an obama drone",
    "al qaeda",
    "melania trump",
    "michelle obama",
    "deadmau5",
    "your boss",
    "slenderman",
    "joseph smith",
    "the mormon church",
    "the pope",
    "bill burr",
    "lady gaga",
    "your neighbor",
    "your dad's best friend that you called \"uncle\" as a child",
    "your real parents",
    "colonel sanders",
    "bernie sanders",
    "the reanimated corpse of steve jobs",
    "eminem",
    "la habra 300 bowl",
    "elon musk",
    "anne frank",
    "marshall pope",
    "shigeru miyamoto",
    "your unwashed ass",
    "She Who Squirts",
    "He Who Cums",
    "Liz's cat",
    "Beemo",
    "the British",
    "bisexuals",
    "papi",
    "a bloody fucker",
    "an actual chimp",
    "shawty",
    "I",
    "Ronald Reagan",
    "Nicolas Cage",
    "Queen Elizabeth",
    "Nickelback",
    "Keanu Reeves",
    "Democrats",
    "Republicans",
    "donald johnald tronald",
    "donald john president",
    "the fall guy",
    "Disney Pixar's Cars™️ Pope Pinion IV",
    "mexican shinji ikari",
    "olm",
    "olmyra",
    "chris",
    "jed sheeran",
    "nick",
    "zach",
    "zavala",
    "ikora",
    "cayde",
    "banshee-44",
    "tess everis",
    "hawthorne",
    "calus",
    "osiris",
    "an actual nigerian prince trying to give you money",
    "donny jr",
    "mara sov",
    "xur",
    "uncle roger",
    "god",
    "your bitchy aunt",
    "your qanon uncle",
    "Q himself",
    "froggy chair",
    "socialists",
    "nazis",
    "communists",
    "John Bungie",
    "Big Oil",
    "Big Pharma",
    "ross from friends",
    "patrick star",
    "squidward",
    "chandler",
    "the shit stain in your underwear",
    "a crusty sock",
    "a cockroach",
    "seinfeld",
    "the bean quean",
    "the far left",
    "the far right",
    "centrists",
    "ben shapiro",
    "jordan peterson",
    "hillary clinton",
    "osama bin laden",
    "the mailman",
    "hamburger helper",
    "rotisserie chicken",
    "your lazy coworker",
    "Todd Howard",
    "amogus",
    "sus guy",
    "jim halpert",
    "popcat",
    "some dumb binch",
    "the CEO of Robinhood",
    "AOC",
    "ted cruz",
    "j cole",
    "elmer fudd",
    "a cum stain",
    "the inventor of Worms the video game",
    "justin timberlake",
    "the area man",
    "a rando",
    "that one friend who never interacts in discord",
    "the pogchamp guy",
    "an idiot who got banned from twitter",
    "mark zuckerberg's lizard offspring",
    "prince philip",
    "prince philip (in dust form)",
    "your best friend",
    "the guy",
    "robert downey jr",
    "morgan freeman",
    "a friendly neighborhood cat",
    "a birb",
    "some ducklings",
    "the person reading this",
    "abby shapiro",
    "a gamer gril",
    "a butterfly, floating peacefully",
    "Hasbulla",
    "the taliban",
    "that one guy with an eyepatch",
    "chet",
    "brad",
    "steven crowder",
    "the vitamin D council",
    "the fish oil triumvirate",
    "egg demon",
    "computer woman",
    "big elephant man",
    "that one guy that shot the ceo",
    "that one healthcare ceo",
    "obamna",
    "jesus h christ",
    "sonic the hedgehog",
    "a pube",
    "glimpmo",
    "diddy",
    "the rothschilds",
    "luigi",
    "the salami lid (it dont fit)",
    "smoog yoa",
    "wrinkled yoa",
    "Darnell Ultra",
    "Choe Biden",
    "the grink",
    "God and Jesus",
    "Mr. Beast",
    "Mr. Breast",
    "The Band 'Trapt' known for their Hit Single 'Headstrong'",
    "18 inch bruh",
    "Non-binary Peter Coin",
    "Thom Yorke",
    "Marceline the Vampire Queen",
    "Rami Malek",
    "Wednesday Addams",
    "Lupita Nyong'o",
    "Saul Goodman",
    "FKA twigs",
    "Flea",
    "Bojack Horseman",
    "Hayao Miyazaki",
    "Daenerys Targaryen",
    "Ethan Hawke",
    "Tracy Chapman",
    "Larry David",
    "Fiona Apple",
    "tony soprano",
    "meryl streep",
    "walter white",
    "beyoncé",
    "jon snow",
    "morgan freeman",
    "darth vader",
    "taylor swift",
    "homer simpson",
    "leonardo dicaprio",
    "hermione granger",
    "tom hanks",
    "katniss everdeen",
    "will smith",
    "ellen ripley",
    "brad pitt",
    "spider-man",
    "oprah winfrey",
    "indiana jones",
    "angelina jolie",
    "harry potter",
    "denzel washington",
    "princess leia",
    "robert downey jr.",
    "deadpool",
    "jennifer lawrence",
    "forrest gump",
    "samuel l. jackson",
    "wolverine",
    "emma watson",
    "iron man",
    "natalie portman",
    "jack sparrow",
    "dwayne johnson",
    "wonder woman",
    "chris evans",
    "the joker",
    "scarlett johansson",
    "james bond",
    "keanu reeves",
    "captain america",
    "johnny depp",
    "black widow",
    "george clooney",
    "batman",
    "gal gadot",
    "thor",
    "chris hemsworth",
    "superman",
    "ryan reynolds",
    "the rock",
    "margot robbie",
    "hannibal lecter",
    "anne hathaway",
    "gandalf",
    "zendaya",
    "neo",
    "charlize theron",
    "sherlock holmes",
    "idris elba",
    "lara croft",
    "jason momoa",
    "the terminator",
    "emma stone",
    "michael corleone",
    "jennifer aniston",
    "the mandalorian",
    "matt damon",
    "loki",
    "nicole kidman",
    "don vito corleone",
    "sandra bullock",
    "black panther",
    "julia roberts",
    "gollum",
    "chris pratt",
    "marty mcfly",
    "tom cruise",
    "hulk",
    "cate blanchett",
    "han solo",
    "viola davis",
    "the flash",
    "hugh jackman",
    "paul cheenis",
    "crunt",
    "John, Paul, George, and Ringo",
    "mold mario",
    "clavicular",
    "Chupapi Munyanyo",
    "chinese bill nye",
    "Mike Jones",
    "el jugador",
    "tim robinson",
    "richard dawkins",
    "a duck sized horse",
    "a horse sized duck",
    "gleepdorf",
    "the Dutch",
    "crumbster",
    "moldmario",
    "Jeff Crump",
    "Peam (the girl)",
    "the baby from eraser head",
    "jimbo",
    "Tommy",
    "B*rnie",
    "Shit the Shatman",
    "the Pee Wench",
    "a podcaster",
    "white people",
    "grunting george",
    "a chopped up UNC",
    "harmabe",
    "throbbert crunt",
    "my personal jester",
    "my evil employee",
    "Puss McCrackin",
    "the 0-18 Wraith on your team",
    "a gouger",
    "the Green Goblin",
    "the Greener Goblin",
    "Art Garfunkle",
    "the skinwalker in this server",
    "your local neighborhood crackhead",
    "the down-and-out who needs a fat bitch",
    "big chungus",
    "Bastard people",
    "The Bitch",
    "a wench",
    "a feckless fool",
    "Alexander Hamilton",
    "Fudgebob Pisspants",
    "Mr. Krabs",
    "Hydrated Yoda",
    "poop butt",
    "glup shitto",
    "Lee Harvey Oswald",
    "John Wilkes Booth",
    "The Indians",
    "a bareback gorilla",
    "real Chinese Maoists",
    "Morgan Trueman",
    "morgan fuckman",
    "the fucker",
    "Herb Alpert (spanish flea guy, not Jim)",
    "Denvis",
    "Elvis",
    "Evils (dark Elvis)",
    "Goodvis (Light Elvis)",
    "the ultimate MILF",
    "my creature",
    "Mohamed Atta",
    "Quinty Spruit Bleeker",
    "enemy lesbians",
    "enemy lesbian nuns",
    "dweebs",
    "the creature",
    "the developers of the Pussy video game series",
    "pro-algae protestor",
    "SirRopestar",
    "an old lady at church",
    "the old HAG",
    "Youthful Joe",
    "Michael Bolton",
    "the demon",
    "souls of the damned",
    "Jack Ingoff (Russian?)",
    "The Master of 1 Hand and Fool of the Other",
    "sickos",
    "Mike Cunt",
    "a chunti woman",
    "the yellow m&m (The Fool)",
    "the green m&m (the sexy one)",
    "a gentleman",
    "the mormos",
    "John Gleep",
    "Juan Gleep",
    "john dicksus",
    "\"Ugly\" Johnny Dickshot",
    "the other james",
    "a man named steve",
    "someone called greg",
    "the guy who keeps saying 'actually'",
    "the person who never returns the shopping cart",
    "the neighbor with the loud leaf blower",
    "the guy from the next apartment",
    "the woman with the clipboard",
    "the person who knows a guy",
    "the friend of a friend",
    "the cousin nobody remembers",
    "the family group chat admin",
    "the guy who brings his own chair",
    "the person who says 'let me play devil's advocate'",
    "the one who always has a charger",
    "the one who never has a charger",
    "the person who says 'quick question'",
    "the guy who claps when the plane lands",
    "the woman who knows all the gossip",
    "the person who replies 'k'",
    "the guy with the folding bike",
    "the person who takes notes at parties",
    "the one who read the terms and conditions",
    "the one who skipped the tutorial",
    "the person who forgot why they walked into the room",
    "the guy who owns six identical hoodies",
    "the woman with the emergency snacks",
    "the person who names every houseplant",
    "the one who never checks the group chat",
    "the guy who says 'we should start a podcast'",
    "the person who takes forever to pick a restaurant",
    "the one who makes everything a spreadsheet",
    "the guy who has a suspicious amount of free time",
    "the person who always arrives exactly seven minutes late",
    "the one who keeps moving the furniture",
    "the guy who brought a thermos",
    "the person who has a backup plan for the backup plan",
    "the one who says 'no offense' before being offensive",
    "the person who asks if there is a dress code",
    "the guy who knows how to fix printers",
    "the person who has never seen the movie everyone is talking about",
    "the one who posts vacation photos in real time",
    "the guy who still uses a paper calendar",
    "the person who leaves one sip in the bottle",
    "the one who sends voice messages instead of texts",
    "the guy who has a podcast microphone",
    "the person who keeps saying they are deleting social media",
    "the one who brings a reusable container to every restaurant",
    "the guy who takes everything literally",
    "the person who insists on being called by their full name",
    "the one who always knows the weather",
    "the guy who has strong opinions about fonts",
    "the person who reads restaurant reviews during dinner",
    "the one who says 'I have an idea' at the worst possible time",
    "the guy who owns a label maker",
    "the person who is somehow already there",
    "the one who cannot remember any passwords",
    "the guy who sends the same meme twice",
    "the person who thinks every problem can be solved with tape",
    "the one who has a very organized junk drawer",
    "the guy who says 'back in my day'",
    "the person who takes the last slice without asking",
    "the one who always forgets their wallet",
    "the guy who brings up cryptocurrency unprompted",
    "the person who has a collection of novelty mugs",
    "the one who says 'it will only take five minutes'",
    "the guy who never mutes himself",
    "the person who replies-all by accident",
    "the one who has an unnecessarily elaborate morning routine",
    "the guy who thinks he could survive in the wilderness",
    "the person who owns a drone but never uses it",
    "the one who has a suspiciously good memory",
    "the guy who keeps calling it a 'hack'",
    "the person who sends calendar invites for casual plans",
    "the one who brings a jacket everywhere",
    "the guy who has an answer for everything",
    "the person who cannot parallel park",
    "the one who always chooses the slowest checkout line",
    "the guy who says 'trust me' with no evidence",
    "the person who is technically not invited",
    "the one who has been waiting on hold since Tuesday",
    "the guy who calls every dog 'buddy'",
    "the person who leaves tabs open for months",
    "the one who thinks the printer is personally targeting them",
    "the guy who has a very specific handshake",
    "the person who brings store-bought cookies in a nice container",
    "the one who has a favorite gas station",
    "the guy who wears sunglasses indoors",
    "the person who always asks for a bite",
    "the one who knows where the good chairs are",
    "the guy who still says 'YOLO'",
    "the person who has an emergency spreadsheet",
    "the one who takes a phone call in the middle of the movie",
    "the guy who tells the same story every Thanksgiving",
    "the person who thinks they are good at impressions",
    "the one who refuses to use automatic checkout",
    "the guy who has a drawer full of batteries",
    "the person who says 'let's circle back'",
    "the one who is always looking for their keys",
    "the guy who has a Bluetooth speaker at the beach",
    "the person who carries too many tote bags",
    "the one who has a complicated coffee order",
    "the guy who says 'I know a shortcut'",
    "the person who keeps receipts for everything",
    "the one who takes screenshots instead of bookmarking",
    "the guy who has a personal vendetta against slow walkers",
    "the person who owns a surprisingly formal hat",
    "the one who sends a thumbs-up and disappears",
    "the guy who thinks every meeting needs an agenda",
    "the person who has a favorite pen",
    "the one who refers to their dog as their roommate",
    "the guy who is always 'five minutes away'",
    "the person who forgot to charge their phone",
    "the one who brings a notebook to the dentist",
    "the guy who has never used a coupon",
    "the person who apologizes to furniture after bumping into it",
    "the one who has a suspiciously detailed emergency plan",
    "the guy who says 'interesting' when he means 'bad'",
    "the person who owns a tiny flashlight",
    "the one who leaves the group chat and immediately rejoins",
    "the guy who keeps offering unsolicited directions",
    "the person who has a favorite parking spot",
    "the one who always picks the restaurant with the longest wait",
    "the guy who takes the phrase 'limited edition' seriously",
    "the person who is somehow related to everyone",
    "the one who calls customer service just to complain",
    "the guy who has a collection of hotel pens",
    "the person who says 'I barely slept' every morning",
    "the one who is holding up the line",
    "the guy who has a suspiciously clean car",
    "the person who keeps saying 'one last thing'",
    "the one who is wearing a lanyard for no reason",
    "the guy who has a strong stance on pineapple pizza",
    "the person who forgot the password to their password manager",
    "the one who refers to the microwave as 'the oven'",
    "the guy who always has exact change",
    "the person who brought a folding chair to the meeting",
    "the one who thinks every restaurant is too loud",
    "the guy who knows every shortcut but never uses one",
    "the person who takes pictures of their food from above",
    "the one who still has an AOL email address",
    "the guy who says 'we'll see' and definitely means no",
    "the person who is banned from the self-checkout",
    "the one who has a surprisingly strong opinion about napkins",
    "the guy who always forgets where he parked",
    "the person who wears a backpack to formal events",
    "the one who keeps a snack in every pocket",
    "the guy who has a favorite chair and will defend it",
    "the person who uses the word 'synergy' sincerely",
    "the one who knows the Wi-Fi password by heart",
    "the guy who is suspicious of automatic doors",
    "the person who says 'I could do that' during documentaries",
    "the one who brings their own hot sauce",
    "the guy who has a very old phone",
    "the person who is always in the wrong group chat",
    "the one who refuses to throw away a good box",
    "the guy who has an unexplained amount of string",
    "the person who says 'this should be easy'",
    "the one who leaves one square of toilet paper on the roll",
    "the guy who has a map in the glove compartment",
    "the person who is still using a cracked screen protector",
    "the one who says 'I don't want to make a big deal out of it' and does",
    "the guy who knows a surprisingly large amount about birds",
    "the person who has a favorite brand of paper towel"
  ],
  "peopleirl": [
    "reeg",
    "james",
    "jimmy",
    "kacey",
    "tyra",
    "liz",
    "ton",
    "cody",
    "ysabel",
    "leah",
    "j",
    "olm",
    "adriana"
  ],
  "erW": [
    "enemy",
    "weak foe",
    "strong foe",
    "monster",
    "dragon",
    "boss",
    "sentry",
    "group",
    "pack",
    "decoy",
    "undead",
    "soldier",
    "knight",
    "cavalier",
    "archer",
    "sniper",
    "mage",
    "ordnance",
    "monarch",
    "lord",
    "demi-human",
    "outsider",
    "giant",
    "horse",
    "dog",
    "wolf",
    "rat",
    "beast",
    "bird",
    "raptor",
    "snake",
    "crab",
    "prawn",
    "octopus",
    "bug",
    "scarab",
    "slug",
    "wraith",
    "skeleton",
    "monstrosity",
    "ill-omened creature",
    "Tarnished",
    "warrior",
    "swordfighter",
    "knight",
    "samurai",
    "sorcerer",
    "cleric",
    "sage",
    "merchant",
    "teacher",
    "master",
    "friend",
    "lover",
    "old dear",
    "old codger",
    "angel",
    "fat coinpurse",
    "pauper",
    "good sort",
    "wicked sort",
    "plump sort",
    "skinny sort",
    "lovable sort",
    "pathetic sort",
    "strange sort",
    "nimble sort",
    "laggardly sort",
    "invisible sort",
    "unfathomable sort",
    "giant sort",
    "sinner",
    "thief",
    "liar",
    "dastard",
    "traitor",
    "pair",
    "trio",
    "noble",
    "aristocrat",
    "hero",
    "champion",
    "monarch",
    "lord",
    "god",
    "item",
    "necessary item",
    "precious item",
    "something",
    "something incredible",
    "treasure chest",
    "corpse",
    "coffin",
    "trap",
    "armament",
    "shield",
    "bow",
    "projectile weapon",
    "armor",
    "talisman",
    "skill",
    "sorcery",
    "incantation",
    "map",
    "material",
    "flower",
    "grass",
    "tree",
    "fruit",
    "seed",
    "mushroom",
    "tear",
    "crystal",
    "butterfly",
    "bug",
    "dung",
    "grace",
    "door",
    "key",
    "ladder",
    "lever",
    "lift",
    "spiritspring",
    "sending gate",
    "stone astrolabe",
    "Birdseye Telescope",
    "message",
    "bloodstain",
    "Erdtree",
    "Elden Ring",
    "close-quarters battle",
    "ranged battle",
    "horseback battle",
    "luring out",
    "defeating one-by-one",
    "taking on all at once",
    "rushing in",
    "stealth",
    "mimicry",
    "confusion",
    "pursuit",
    "fleeing",
    "summoning",
    "circling around",
    "jumping off",
    "dashing through",
    "brief respite",
    "Actions\t",
    "attacking",
    "jump attack",
    "running attack",
    "critical hit",
    "two-handing",
    "blocking",
    "parrying",
    "guard counter",
    "sorcery",
    "incantation",
    "skill",
    "summoning",
    "throwing",
    "healing",
    "running",
    "rolling",
    "backstepping",
    "jumping",
    "crouching",
    "target lock",
    "item crafting",
    "gesturing",
    "morning",
    "noon",
    "evening",
    "night",
    "clear sky",
    "overcast",
    "rain",
    "storm",
    "mist",
    "snow",
    "patrolling",
    "procession",
    "crowd",
    "surprise attack",
    "ambush",
    "pincer attack",
    "beating to a pulp",
    "battle",
    "reinforcements",
    "ritual",
    "explosion",
    "high spot",
    "defensible spot",
    "climbable spot",
    "bright spot",
    "dark spot",
    "open area",
    "cramped area",
    "hiding place",
    "sniping spot",
    "recon spot",
    "safety",
    "danger",
    "gorgeous view",
    "detour",
    "hidden path",
    "secret passage",
    "shortcut",
    "dead end",
    "looking away",
    "unnoticed",
    "out of stamina",
    "Places\t",
    "high road",
    "checkpoint",
    "bridge",
    "castle",
    "fort",
    "city",
    "ruins",
    "church",
    "tower",
    "camp site",
    "house",
    "cemetery",
    "underground tomb",
    "tunnel",
    "cave",
    "evergaol",
    "great tree",
    "cellar",
    "surface",
    "underground",
    "forest",
    "river",
    "lake",
    "bog",
    "mountain",
    "valley",
    "cliff",
    "waterside",
    "nest",
    "hole",
    "east",
    "west",
    "south",
    "north",
    "ahead",
    "behind",
    "left",
    "right",
    "center",
    "up",
    "down",
    "edge",
    "head",
    "stomach",
    "back",
    "arms",
    "legs",
    "rump",
    "tail",
    "core",
    "fingers",
    "physical",
    "standard",
    "striking",
    "slashing",
    "piercing",
    "fire",
    "lightning",
    "magic",
    "holy",
    "poison",
    "toxic",
    "scarlet rot",
    "blood loss",
    "frost",
    "sleep",
    "madness",
    "death",
    "life",
    "Death",
    "light",
    "dark",
    "stars",
    "fire",
    "Order",
    "chaos",
    "joy",
    "wrath",
    "suffering",
    "sadness",
    "comfort",
    "bliss",
    "misfortune",
    "good fortune",
    "bad luck",
    "hope",
    "despair",
    "victory",
    "defeat",
    "research",
    "faith",
    "abundance",
    "rot",
    "loyalty",
    "injustice",
    "secret",
    "opportunity",
    "pickle",
    "clue",
    "friendship",
    "love",
    "bravery",
    "vigor",
    "fortitude",
    "confidence",
    "distracted",
    "unguarded",
    "introspection",
    "regret",
    "resignation",
    "futility",
    "on the brink",
    "betrayal",
    "revenge",
    "destruction",
    "recklessness",
    "calmness",
    "vigilance",
    "tranquility",
    "sound",
    "tears",
    "sleep",
    "depths",
    "dregs",
    "fear",
    "sacrifice",
    "ruin",
    "good luck",
    "look carefully",
    "listen carefully",
    "think carefully",
    "well done",
    "I did it!",
    "I've failed...",
    "here!",
    "not here!",
    "don't you dare!",
    "do it!",
    "I can't take this...",
    "don't think",
    "so lonely...",
    "here again...",
    "just getting started",
    "stay calm",
    "keep moving",
    "turn back",
    "give up",
    "don't give up",
    "help me...",
    "I don't believe it...",
    "too high up",
    "I want to go home...",
    "it's like a dream...",
    "seems familiar...",
    "beautiful...",
    "you don't have the right",
    "are you ready?"
  ],
  "erP": [
    "{w} ahead",
    "Likely {w}",
    "If only I had a {w}",
    "{w}, O {w}",
    "Ahh, {w}",
    "No {w} ahead",
    "First off, {w}",
    "Didn't expect {w}...",
    "Behold, {w}!",
    "{w}",
    "{w} required ahead",
    "Seek {w}",
    "Visions of {w}...",
    "Offer {w}",
    "{w}!",
    "Be wary of {w}",
    "Still no {w}...",
    "Could this be a {w}?",
    "Praise the {w}",
    "{w}?",
    "Try {w}",
    "Why is it always {w}?",
    "Time for {w}",
    "Let there be {w}",
    "{w}..."
  ],
  "erC": [
    "and then",
    "or",
    "but",
    "therefore",
    "in short",
    "except",
    "by the way",
    "so to speak",
    "all the more",
    ","
  ],
  "things": [
    "poop",
    "in n out double double",
    "french fries",
    "a coffee",
    "hand lotion",
    "nothing",
    "alcohol",
    "hand sanitizer",
    "yeast",
    "magnets",
    "a solved rubiks cube",
    "piss from the piss drawer",
    "sad minion memes",
    "sharp objects",
    "a cat",
    "an ICE detention center",
    "a human child",
    "a bullet",
    "a rose",
    "a gun",
    "a bomb",
    "a silent fart that smells really bad",
    "a loud fart that goes unnoticed",
    "a shit you dont have to wipe",
    "a bottle of vodka",
    "a field mouse",
    "a barn cat",
    "a 1999 Toyota Corolla",
    "a semi truck full of eggs",
    "the true meaning of Christmas",
    "last year's cum sock (reborn)",
    "last year's cum sock (deceased)",
    "the source of J's power",
    "the vomit coffin",
    "the manifestation of your innermost fears",
    "the incarnation of guilt",
    "a lesser manifestation of evil",
    "the origin of cum",
    "an erect penis",
    "a flaccid penis",
    "a docile, but friendly penis",
    "an aggressive penis",
    "nothing. It's nothing. Stop fucking asking!",
    "an old pioneer survivalist strategy",
    "my left shoe",
    "a rock",
    "a boulder",
    "bees",
    "hot sauce",
    "scotch tape",
    "a breathmint",
    "a facemask",
    "a half eaten bar of chapstick",
    "some scrap metal",
    "a trashbag full of cum",
    "a rusty bicycle",
    "blood",
    "tears of the natives",
    "a crusty keyboard",
    "a half eaten burrito",
    "a mug of cold coffee",
    "a job offer",
    "nasal spray",
    "a bidet that shoots milk",
    "an old toothbrush",
    "a pen that ran out of ink",
    "tupperware full of moldy leftovers",
    "a white flag",
    "fake news",
    "the failed coup attempt perpetrated by fascist Trump supporters on the United States capitol on Jan 6, 2021",
    "Microsoft Outlook 2013",
    "lifesavers gummies",
    "a kit kat bar",
    "a newborn chimp",
    "an adult boar",
    "a dead cockroach",
    "a horny dog",
    "The Beast",
    "a succulent that you overwatered",
    "a shard of glass",
    "a honeycomb",
    "a half eaten sandwich",
    "the worst, most disgusting, carnal fantasy you've ever had",
    "a shit you definitely should have wiped",
    "a shit you wish you didn't wipe",
    "a protein bar that is well past the expiration date",
    "a pair of shit-stained underwear",
    "an asshole",
    "a really nice business card",
    "an electric fly swatter",
    "a stress ball that oozes blood",
    "a molotov cocktail",
    "an AK-47",
    "a dirty old shoe",
    "a hairball from the shower drain",
    "bad noodle",
    "a single atom",
    "a puddle of cooking oil",
    "a piss disc mid-air",
    "a t-shirt cannon",
    "a volleyball with a face",
    "in n out fries",
    "cheam creems",
    "spinch",
    "ranibow sprimkle",
    "chichen nuggest",
    "mcdonald's sprite",
    "chick fil a sauce",
    "poopy doopy wee wee haha",
    "a jar of honey",
    "a comfortable sweater",
    "an ugly, scratchy sweater",
    "a water balloon full of vinegar",
    "a can of pringles but they are all broken",
    "a dead pig",
    "dirty stripper shoes",
    "super glue",
    "a pen that ran dry ages ago",
    "an spicey meatbole",
    "a laptop with sticky keys",
    "underwear lint",
    "a sundress",
    "a funko pop of your least favorite anime character",
    "a security camera",
    "hawaiian green bean pizza",
    "my hairy ass",
    "a taint hair",
    "beast sandwich",
    "my left nut",
    "shmedium",
    "cheesy garlic bread",
    "ten gigs worth of women's butts",
    "a lime scooter",
    "a bullet casing",
    "pork juice",
    "crust",
    "a nice pen",
    "Obamunism",
    "Paul’s Cheenis",
    "good ONE",
    "Epstein’s Fortnite account",
    "goth boots",
    "coffee",
    "chia seeds",
    "some nice tea with honey",
    "shit from a butt",
    "poop from an ass",
    "a single poop from two asses",
    "piss",
    "file.data",
    "stinky cheese",
    "100 beers in 1 month",
    "a fiery cum explosion",
    "a pipe made from the hollowed out corpse of the baby from eraserhead",
    "gentleman's relish",
    "zygote zest",
    "generational brown no wipe any%",
    "a street cat",
    "a mangy dog",
    "the 10 minute japanese youtube poop",
    "a double chili cheeseburger",
    "way too big nuts",
    "my fat nuts on discord",
    "Nicki Minaj's cousin's friend's swollen nuts (vaccine injury)",
    "haunted moon",
    "the legend of the penis",
    "a non-threatening penis",
    "harmful isotopes",
    "cheenis",
    "a handful of doinks",
    "a used condom",
    "Pablo Escobar's heard of 80 feral hippos",
    "ooey gooey corporate synergy",
    "2 purple dildos delivered in the mail",
    "a delicious Baja Blast",
    "fat walnuts",
    "the Sinclair dinosaur",
    "a lightly chiefed blunt",
    "Ton's house",
    "中华 (Zhōnghuá): the eternal heart of our people",
    "SIKMOQ HAMMA DELIKATES PESHTAXTA ODAMLAR",
    "caca in my toilet",
    "worthless hole",
    "the green fool's most shameful appendage",
    "hole",
    "penis music",
    "breasts image",
    "a delicious pie in the windowsill",
    "the power of ass to mouth resuckitation",
    "penus",
    "fillet o fish",
    "a succulent Chinese meal",
    "millennial humor",
    "Gen Z slang",
    "bone hurting juice",
    "a corpse",
    "onion rings",
    "binky",
    "=roleplay",
    "a jar of peanut butter pretzels",
    "diarrhea",
    "a guy",
    "a cheery disposition",
    "gnung munch",
    "neck",
    "a hankering curiosity",
    "tact",
    "SpongeBob meme",
    "a heart full of hate",
    "the middle finger",
    "a lust for life",
    "eggs",
    "racism",
    "a slur that hasn’t even been invented yet",
    "200 lemmings poised on the edge",
    "a child’s sock you found in your laundry (you have no children)",
    "the super sucker cum jetting machine",
    "wordle",
    "beans",
    "sticky appendage",
    "15 babies",
    "youthful stride",
    "gimmicks",
    "chicanery",
    "love",
    "milk in a dirty glass",
    "I don’t know",
    "the demon’s spawn",
    "brujeria",
    "prayers",
    "ointment",
    "Markiplier’s Sinister Potion",
    "Snarkiplier's Minister Potion",
    "the spores",
    "nerds gummy clusters",
    "a desk plant",
    "a baseball",
    "a stapler",
    "a rubber duck",
    "a flosspick",
    "a coffee mug",
    "a calculator",
    "a rubber stamp",
    "a bottle of honey",
    "a roll of tape",
    "a wristwatch",
    "a hydroflask™ bottle",
    "a lumbar support pillow",
    "a wall calendar",
    "a webcam",
    "a button-cell battery",
    "a parking ticket",
    "a cracked phone screen",
    "a half-charged power bank",
    "a receipt from a place that closed years ago",
    "a dead houseplant",
    "a box of mismatched screws",
    "a bent spoon",
    "a missing puzzle piece",
    "a suspiciously damp towel",
    "a grocery bag full of other grocery bags",
    "a jar of loose change",
    "a broken umbrella",
    "a takeout menu from 2014",
    "a single oven mitt",
    "a tangled extension cord",
    "a nearly empty bottle of ketchup",
    "a pack of gum with one piece left",
    "a dusty board game",
    "a half-used notebook",
    "a burnt CD with no label",
    "a dead battery",
    "a lint-covered hoodie",
    "a drawer full of pens that do not work",
    "a wet cardboard box",
    "a small bag of gravel",
    "a cracked coffee mug",
    "a lukewarm soda",
    "a forgotten library book",
    "a bent coat hanger",
    "a cheap pair of sunglasses",
    "a box of stale crackers",
    "a loose shoelace",
    "a nearly empty bottle of shampoo",
    "a coupon that expired last month",
    "a plastic container with no lid",
    "a lid with no container",
    "a dusty router",
    "a roll of paper towels with one sheet left",
    "a half-eaten granola bar",
    "a freezer-burned burrito",
    "a suspiciously old banana",
    "a bag of rice with a torn corner",
    "a broken tape measure",
    "a bent fork",
    "a shoebox full of cables",
    "a small folding chair",
    "a dead flashlight",
    "a forgotten password written on a napkin",
    "a grocery list with no groceries",
    "a cracked picture frame",
    "a loose button",
    "a bottle of water from the car",
    "a roll of tape that has lost its edge",
    "a dusty keyboard",
    "a single earbud",
    "a cold slice of pizza",
    "a packet of soy sauce",
    "a takeout fork",
    "a half-empty jar of salsa",
    "a bag of chips with mostly air",
    "a flat tire",
    "a missing remote",
    "a stack of unopened mail",
    "a broken alarm clock",
    "a chair with one slightly shorter leg",
    "a shopping cart with a bad wheel",
    "a faded birthday card",
    "a nearly empty bottle of dish soap",
    "a loose screw from an unknown object",
    "a cracked plastic hanger",
    "a box of outdated batteries",
    "a half-used roll of wrapping paper",
    "a mug that says 'World's Best Boss'",
    "a calendar from last year",
    "a cold cup of coffee",
    "a soggy napkin",
    "a dusty fan",
    "a single chopstick",
    "a badly folded fitted sheet",
    "a grocery receipt for one item",
    "a bag of frozen peas",
    "a dented can of soup",
    "a plastic fork snapped in half",
    "a mostly empty bottle of hot sauce",
    "a roll of quarters",
    "a cracked phone charger",
    "a packet of ketchup",
    "a cheap wristwatch",
    "a bent license plate",
    "a box of old photographs",
    "a dead marker",
    "a half-empty bottle of hand soap",
    "a scratched DVD",
    "a small piece of sidewalk chalk",
    "a damp pair of socks",
    "a tangled pair of headphones",
    "a single shoelace",
    "a box of cereal with no prize",
    "a nearly empty jar of peanut butter",
    "a worn-out backpack",
    "a dusty pair of binoculars",
    "a forgotten birthday candle",
    "a plastic bag full of receipts",
    "a broken calculator",
    "a half-used roll of aluminum foil",
    "a bag of stale popcorn",
    "a paper plate with one olive on it",
    "a bottle of salad dressing nobody likes",
    "a missing cabinet handle",
    "a cracked ice cube tray",
    "a stack of takeout menus",
    "a dead plant labeled 'basil'",
    "a single sock behind the dryer",
    "a jar of pennies",
    "a bent ruler",
    "a half-empty bottle of lotion",
    "a cardboard box marked 'miscellaneous'",
    "a dusty alarm clock",
    "a scratched pair of sunglasses",
    "a plastic container full of mystery leftovers",
    "a broken stapler",
    "a roll of receipt paper",
    "a tiny packet of tissues",
    "a forgotten umbrella",
    "a stale tortilla",
    "a cold french fry",
    "a mostly empty bag of flour",
    "a takeout container with no lid",
    "a lid with no takeout container",
    "a single rubber band",
    "a broken zipper",
    "a stack of old coupons",
    "a receipt with an unusually high total",
    "a phone charger that only works at one angle",
    "a drawer full of batteries of different sizes",
    "a pair of gloves that do not match",
    "a cracked serving tray",
    "a half-empty jar of pickles",
    "a box of pens with one working pen",
    "a faded sticker",
    "a dusty bottle of vitamins",
    "a bag of flour with a tear in it",
    "a plastic cup from a concert",
    "a cold bowl of oatmeal",
    "a single unopened condiment packet",
    "a box of tissues with one tissue left",
    "a bent metal straw",
    "a small pile of receipts",
    "a coffee mug full of coins",
    "a torn instruction manual",
    "a broken picture hanger",
    "a slightly crooked wall clock",
    "a folder full of documents nobody needs",
    "a jar of expired spices",
    "a loose shoelace aglet",
    "a half-used candle",
    "a bag of onions with one bad onion",
    "a chipped plate",
    "a dented water bottle",
    "a dusty bottle of barbecue sauce",
    "a plastic container full of dry pasta",
    "a single unclaimed key",
    "a worn-out welcome mat",
    "a broken clothes hanger",
    "a stack of junk mail",
    "a cold hard-boiled egg",
    "a nearly empty bottle of vinegar",
    "a paper grocery bag with a hole in it",
    "a small pile of loose screws",
    "a scratched pair of reading glasses",
    "a forgotten lunch in the back of the fridge",
    "a half-empty jar of mayonnaise",
    "a torn piece of notebook paper",
    "a folding chair nobody trusts",
    "a dead smoke detector",
    "a box of old phone chargers",
    "a single expired gift card",
    "a cracked plastic storage bin",
    "a dusty bottle of aspirin",
    "a bent can opener",
    "a half-eaten apple",
    "a stack of coasters",
    "a bag of ice that has mostly melted",
    "a broken kitchen timer",
    "a bottle of water with no label",
    "a roll of tape stuck to itself",
    "a grocery bag containing one potato",
    "a chipped bowl",
    "a single paper napkin",
    "a box of assorted screws",
    "a nearly empty tube of toothpaste",
    "a dead wireless mouse",
    "a tangled Christmas light strand",
    "a plastic container of unidentified sauce",
    "a dusty bottle of sunscreen",
    "a bent pair of tongs",
    "a half-empty jar of olives",
    "a cracked cutting board",
    "a stack of unread magazines",
    "a broken pencil sharpener",
    "a single loose shoelace",
    "a forgotten takeout order",
    "a box of tea bags nobody wants",
    "a nearly empty bottle of soy sauce",
    "a scratched-up lunchbox",
    "a small pile of unmatched socks",
    "a broken doorstop",
    "a stale bagel",
    "a plastic bag full of plastic bags",
    "a crooked picture of a beach",
    "a bottle of vitamins from 2017",
    "a cold tortilla",
    "a single dried-out marker",
    "a drawer containing one fork, two batteries, and a key",
    "a receipt for a suspiciously large amount of cheese",
    "a half-empty bottle of ranch",
    "a dusty extension cord",
    "a chair that is technically usable",
    "a box of cereal with the bag already open",
    "a small amount of loose glitter",
    "a cracked mirror",
    "a broken remote control",
    "a grocery list written in someone else's handwriting",
    "a jar of mystery powder",
    "a half-used bottle of window cleaner",
    "a single cold chicken nugget",
    "a dented thermos",
    "a stack of papers with no apparent purpose",
    "a broken umbrella in a trash can",
    "a nearly empty bag of sugar",
    "a plastic cup full of pens",
    "a box labeled 'important' containing nothing useful",
    "a dead spider in the windowsill",
    "a damp cardboard receipt",
    "a lone tortilla chip",
    "a bottle of ketchup with no cap",
    "a pair of scissors that only cuts paper badly",
    "a half-empty bag of croutons",
    "a dusty can of beans",
    "a broken hanger",
    "a single coin from another country",
    "a bag of trail mix with no chocolate pieces",
    "a cracked ceramic ashtray",
    "a cold cup of tea",
    "a box of cables for devices nobody owns",
    "a chair with a coat on it",
    "a missing puzzle box",
    "a half-empty bottle of dishwashing liquid",
    "a folded receipt used as a bookmark",
    "a container of leftovers from an unknown year",
    "a small bag of popcorn kernels",
    "a single clean sock",
    "a dusty bottle of mustard",
    "a worn-out pencil",
    "a bent paperclip",
    "a nearly empty jar of instant coffee",
    "a box of bandages with one left",
    "a broken keychain",
    "a stack of old takeout containers",
    "a cold pancake",
    "a mildly threatening voicemail",
    "a voicemail from an unknown number",
    "an email marked 'urgent' about nothing",
    "a group chat nobody has spoken in since 2019",
    "a password hint that makes things less clear",
    "a calendar reminder for something that already happened",
    "a text message that only says 'never mind'",
    "a missed call from your own number",
    "a meeting that could have been an email",
    "a browser tab you are afraid to close",
    "a notification with no useful information",
    "a receipt that says 'thank you' but does not",
    "a note that says 'call me' with no name",
    "a spreadsheet with one unexplained cell",
    "a document titled 'final_final_revised2'",
    "a file named 'new folder (7)'",
    "a printer that needs emotional support",
    "a customer service chatbot that keeps apologizing",
    "a loading screen stuck at 99 percent",
    "a forgotten PIN written in invisible ink",
    "a calendar invite with no location",
    "a low-battery warning at 47 percent",
    "a work email sent at 3:12 a.m.",
    "a password reset email you did not request",
    "a meeting room with no chairs",
    "a printer error with no explanation",
    "a suspiciously specific warning label",
    "a form with one mandatory field too many",
    "a receipt that lists an item as 'miscellaneous'",
    "a customer loyalty card with no points",
    "a voicemail that is mostly breathing",
    "a group project with one person doing everything",
    "a vending machine that ate your money",
    "a self-checkout that needs assistance",
    "a public restroom hand dryer that does nothing",
    "a shopping cart with one bad wheel",
    "a revolving door moving too slowly",
    "a hotel pillow with a decorative towel on it",
    "a restaurant menu with no prices",
    "a door marked 'employees only'",
    "a waiting room magazine from 2016",
    "a parking meter showing the wrong time",
    "a bus schedule nobody understands",
    "a street sign covered by a tree",
    "a crosswalk button that does not seem connected",
    "a public bench that is still wet",
    "a revolving door that makes a concerning noise",
    "a vending machine offering one item",
    "a hotel room key that stops working immediately",
    "a grocery store announcement nobody can hear",
    "a shopping basket with a broken handle",
    "a self-checkout receipt longer than the purchase",
    "a restaurant table that rocks",
    "a napkin dispenser that gives you six napkins",
    "a public bathroom sink with no soap",
    "a parking spot that is technically too small",
    "a bus seat with something sticky on it",
    "a streetlight that flickers at exactly the wrong time",
    "a door that says pull when it clearly means push",
    "a coin-operated machine that takes only exact change",
    "a hand dryer that sounds like a jet engine",
    "a motel painting of a lake",
    "a cafeteria fork with a mysterious bend",
    "a checkout line that stops moving",
    "a waiting room with no visible receptionist",
    "a sign with an unnecessary apostrophe",
    "a public clock that is seven minutes slow",
    "a parking ticket tucked under the windshield wiper",
    "a bathroom stall with a broken lock",
    "a hotel remote with too many buttons",
    "a store speaker playing the same song again",
    "a restaurant chair with a loose leg",
    "a shopping cart that pulls left",
    "a doorbell that rings twice",
    "a bus stop with no bench",
    "a paper towel dispenser that gives you one sheet at a time",
    "a gas pump that asks if you want a car wash",
    "a plastic bag that is somehow inside another plastic bag",
    "a public fountain full of coins",
    "a parking garage ticket that has already faded",
    "a vending machine with one blinking button",
    "a hotel hallway with no room 13",
    "a grocery receipt listing something you did not buy",
    "a restaurant menu with one item crossed out",
    "a sign that says 'please be patient' with no further explanation",
    "a customer service number that immediately disconnects",
    "a printer that prints everything slightly crooked",
    "a chair labeled 'do not sit'",
    "a door that opens into another door",
    "a traffic cone that has been moved three feet",
    "a public trash can with no bag",
    "a waiting room television with the volume muted",
    "a bathroom mirror that makes you look slightly worse",
    "a tiny packet of crackers from an airplane",
    "a receipt folded into a very small square",
    "a parking space occupied by a shopping cart",
    "a vending machine sandwich",
    "a coffee shop table with one uneven leg",
    "a hotel breakfast waffle that is somehow cold",
    "a public sign missing one important word",
    "a suspiciously clean ashtray",
    "a stapler that is out of staples",
    "a pen chained to a counter",
    "a clipboard with no paper on it",
    "a security camera pointed at the wrong wall",
    "a phone charger that belongs to nobody",
    "a door propped open with a brick",
    "a bowl of mints that are all stuck together",
    "a box of tissues with no tissues",
    "a waiting room chair with a magazine underneath it",
    "a takeout bag containing someone else's order",
    "a parking lot puddle of unknown depth",
    "a receipt with a handwritten phone number",
    "a vending machine that hums too loudly",
    "a forgotten umbrella by the door",
    "a hotel soap that is too small to use",
    "a restaurant straw wrapper shaped like a worm",
    "a grocery store freezer with one empty shelf",
    "a public restroom mirror with one missing screw",
    "a convenience store hot dog that has been rotating too long",
    "a desk drawer full of rubber bands",
    "a stack of forms that all ask the same question",
    "a pen that works only upside down",
    "a wall clock with no hands",
    "a single glove on a park bench",
    "a mystery stain on a carpet",
    "a box of printer paper with one sheet missing",
    "a calendar featuring an animal that looks disappointed",
    "a bottle of water someone left in a conference room",
    "a takeout menu with a phone number crossed out",
    "a public trash can that is somehow full of receipts",
    "a chair that has clearly been repaired before",
    "a coffee stirrer with no coffee",
    "a door handle that is slightly sticky",
    "a small plant in a large pot"
  ],
  "times": [
    "right now",
    "right this second :gun:",
    "in a few minutes",
    "in half an hour",
    "in an hour",
    "in a few hours",
    "tonight",
    "today",
    "tomorrow",
    "the day after tomorrow",
    "exactly 30 minutes from now",
    "in one week",
    "never",
    "at an uncertain point in the annals of history",
    "at tooth-hurty :tooth: :toothbrush:",
    "time is merely a construct",
    "TIME IS MERELY A CONSTRUCT",
    "at six, gordon!",
    "at 4:20 XDDDDDDD",
    "on 4/20 XDDDDDDD",
    "when hell freezes over",
    "when rush limbaugh died",
    "when marvel vs capcom 4 comes out",
    "when james stops bitching about sauce",
    "when final fantasy 7 remake is finished",
    "when team fortress 3 comes out",
    "when bernie sanders is elected",
    "when you fucking do something about it yourself",
    "when the imposter stops being sus",
    "at twelve bong",
    "when half life 3 comes out",
    "yesterday",
    "before you were born",
    "last tuesday",
    "when daft punk breaks up... oh",
    "whenever that franz dude got shot",
    "at dinner time",
    "when yandere simulator comes out",
    "When Bungie goes bankrupt",
    "when Papa Biden gives me the stimmy wimmy uwu",
    "when James embraces the void",
    "when the void calls me back",
    "when Duman brings me the wine",
    "whe Johoise brings me the wine",
    "when the people revolt",
    "the heat death of my anus",
    "the heat death of your anus",
    "at the beginning of the mass ejaculation event (tbd)",
    "in the middle of the mass ejaculation event",
    "at the end of the mass ejaculation event",
    "in 34 minutes and 19 seconds",
    "at around tree fiddy",
    "when ICP discovers how magnets work",
    "when your shit smells like roses",
    "when we are all vaccinated",
    "when Trump dies while choking on a clump of shit and hair",
    "in 3 days",
    "in 7 weeks",
    "in 2 months",
    "in 5 years",
    "one year from today this very minute",
    "when i discover who the FUCK invented beans",
    "when i die",
    "in a little bit...",
    "i am not sure, really",
    "eventually",
    "shortly, just wait!",
    "never..",
    "when you least expect it..",
    "when you admit you have a problem",
    "when they admit they have a problem",
    "while you are sleeping",
    "next time you fart",
    "immediately",
    "when you get off your ASS",
    "2 years from yesterday",
    "next week",
    "next sunday at 11am",
    "next wednesday at 4:19pm",
    "tomorrow morning",
    "when pigs fly",
    "the fifth of never",
    "02/30/25",
    "once in a blue moon",
    "when hell freezes over",
    "13/13/13",
    "at the crack of doom",
    "00/00/00",
    "when gta 6 comes out",
    "the twelfth of whenever",
    "at the end of time",
    "32/12/24",
    "when the cows come home",
    "99/99/99",
    "half past a monkey's ass",
    "when portal 3 gets announced",
    "eleventy-first day of smarch",
    "during the heat death of the universe",
    "29/02/23",
    "when the lakers win another championship",
    "between now and eventually",
    "when tesla makes a $25k car",
    "february 31st",
    "during the next solar eclipse",
    "25:61 pm",
    "when twitter becomes useful",
    "the day after forever",
    "when we discover aliens",
    "π o'clock",
    "the last tuesday of next week",
    "when facebook dies",
    "smarch 15th",
    "the year 20xx",
    "when netflix fixes its ui",
    "the 10th of october",
    "when half-life 3 releases",
    "the 40th hour of the day",
    "when the iphone gets usb-c",
    "the 13th month",
    "when the metaverse is cool",
    "the 32nd of december",
    "when windows stops updating",
    "the 60th minute",
    "when disney buys everything",
    "the first of octember",
    "when minecraft 2 comes out",
    "the 99th second",
    "when google+ makes a comeback",
    "the 25th hour",
    "when reddit becomes readable",
    "the day of the 53rd moon",
    "when the sun rises in the west",
    "the 0th of crunt",
    "during the next total societal collapse",
    "when the last blockbuster closes",
    "on the 100th day of quarantine",
    "when apple makes a touchscreen mac",
    "at the dawn of the third age of mankind",
    "when the cyberpunk 2077 dlc drops",
    "the 29th of february 2023",
    "when skynet goes live",
    "in the year 2525",
    "when the dollar collapses",
    "on the day the music dies",
    "when the elder scrolls 6 releases",
    "at the heat death of the universe",
    "when the beatles reunite",
    "on the 13th of octovember",
    "when twitter adds an edit button",
    "at the end of the infinity war",
    "when the last tweet is sent",
    "on the eve of robot uprising",
    "when the simpsons finally end",
    "during the next great meme war",
    "when netflix stops canceling shows",
    "on the day the internet dies",
    "when the mars colony is established",
    "at the turn of the next ice age",
    "when the last boomer posts on facebook",
    "on the 3th of junuary",
    "when the last bitcoin is mined",
    "during the next zuckerberg apology tour",
    "when the queen’s gambit season 2 drops",
    "on the 100th anniversary of sliced bread",
    "when the emoji movie wins an oscar",
    "at the start of the next pandemic",
    "when the last fax machine is destroyed",
    "on the day the aliens make contact",
    "when the last human leaves earth",
    "at the peak of the next crypto crash",
    "when the matrix glitches",
    "on the 404th day of the year",
    "when the first ai president is elected",
    "during the next great social media migration",
    "when the last dvd player stops working",
    "on the day the robots unionize",
    "when the last magazine is printed",
    "at the moment time travel is invented",
    "when the last vhs tape degrades",
    "on the 99th anniversary of the ipod",
    "when the first meme becomes sentient",
    "at the exact second nostalgia dies",
    "when asses learn to wipe themselves",
    "when you forgive yourself",
    "when the clock strokes its shit its got lotion on its shit it's horny as fuuuuck",
    "lunch time",
    "when the penne explodes",
    "when gleep is added to the dictionary",
    "when your nuts go back to normal size",
    "now",
    "4:59PM",
    "sometime",
    "the moon hits your eye like a big pizza pie, that's amore",
    "idk",
    "crunt o'clock",
    "when angels deserve to die (SOAD 😃)",
    "when you JUST got super comfy on the couch",
    "9/11",
    "when you turn that frown upside down 🙂",
    "gnungus o’clock",
    "in ten minutes",
    "in twenty minutes",
    "in forty-five minutes",
    "in ninety minutes",
    "in two hours",
    "in six hours",
    "in twelve hours",
    "in three days",
    "in four business days",
    "in about a week",
    "in two weeks",
    "in six months",
    "in roughly a year",
    "sometime this afternoon",
    "sometime before lunch",
    "sometime after lunch",
    "late tonight",
    "early tomorrow morning",
    "tomorrow afternoon",
    "tomorrow night",
    "next weekend",
    "next month",
    "sometime this century",
    "before the coffee gets cold",
    "after one more episode",
    "once I finish this one thing",
    "when the laundry is done",
    "after the dishes",
    "when the food gets here",
    "after the meeting",
    "before the meeting that could have been an email",
    "when the printer starts working",
    "after the software update",
    "when the download finishes",
    "once the battery hits 100 percent",
    "when the Wi-Fi comes back",
    "after I find my keys",
    "when I remember what I was doing",
    "after the alarm goes off again",
    "when the snooze button gives up",
    "as soon as I get comfortable",
    "right after I sit down",
    "the moment I stop looking for it",
    "when the leftovers are gone",
    "after the leftovers become questionable",
    "when the takeout arrives",
    "after one more snack",
    "at breakfast",
    "at brunch",
    "around lunchtime",
    "at the usual time",
    "whenever the microwave beeps",
    "when the oven timer goes off",
    "after the kettle boils",
    "when the ice melts",
    "once the coffee kicks in",
    "before the coffee kicks in",
    "after the second coffee",
    "when the sun goes down",
    "at sunset",
    "after dark",
    "before sunrise",
    "at sunrise",
    "in the middle of the night",
    "at an unreasonable hour",
    "during normal business hours",
    "outside normal business hours",
    "at the end of the workday",
    "five minutes before closing",
    "right before the weekend",
    "on a weekday",
    "on the weekend",
    "next Monday",
    "this coming Friday",
    "the next time it rains",
    "after the next awkward silence",
    "when nobody is watching",
    "when everyone is finally ready",
    "after everyone says they are ready",
    "when the group chat responds",
    "after the group chat changes the subject",
    "when the last person arrives",
    "once the line starts moving",
    "when the elevator gets here",
    "after the elevator stops at every floor",
    "when the traffic clears",
    "after the train passes",
    "when the bus shows up",
    "when the parking spot opens",
    "after I find parking",
    "when the light turns green",
    "at the next red light",
    "after the detour ends",
    "when the weather app is correct",
    "during the next power outage",
    "when the smoke alarm stops chirping",
    "after the repair person leaves",
    "when the landlord responds",
    "after the paperwork is approved",
    "when the check clears",
    "after payday",
    "before payday",
    "at the end of the month",
    "on the first of the month",
    "after rent is due",
    "when the bill stops being confusing",
    "after the bank holiday",
    "during tax season",
    "when the package is delivered",
    "after the package gets marked delivered",
    "when the tracking number updates",
    "once the return is processed",
    "after customer service replies",
    "when the hold music ends",
    "after the automated message",
    "when the password reset works",
    "after I find the right cable",
    "when the charger is at the right angle",
    "once the tab stops buffering",
    "after the website accepts the form",
    "when the captcha recognizes me",
    "after the printer finds paper",
    "when the ink is replaced",
    "when the document is actually final",
    "after final_final_revised3",
    "when the file finishes uploading",
    "after the backup completes",
    "when the computer stops updating",
    "once the notification disappears",
    "after I clear my inbox",
    "when the email thread ends",
    "after the calendar reminder",
    "when the appointment is confirmed",
    "at the next available appointment",
    "when the doctor calls back",
    "after the dentist appointment",
    "when the soreness goes away",
    "after the headache passes",
    "when I feel like going outside",
    "after I take a shower",
    "once the towel is dry",
    "when the clothes finish drying",
    "after I fold the laundry",
    "when I find the other sock",
    "after I clean the room",
    "when the room gets messy again",
    "before I go to bed",
    "after I wake up",
    "once I have had enough sleep",
    "when I stop being tired",
    "after the nap",
    "before the nap turns into bedtime",
    "when the alarm is no longer relevant",
    "at the point of no return",
    "just before I change my mind",
    "immediately after changing my mind",
    "when I get around to it",
    "once I remember",
    "after I write it down",
    "when I stop procrastinating",
    "after the deadline",
    "five minutes before the deadline",
    "during the last possible minute",
    "when it becomes an emergency",
    "after someone says 'quick question'",
    "once the situation escalates",
    "when the problem fixes itself",
    "after making it worse",
    "when the instructions make sense",
    "after reading the instructions",
    "before reading the instructions",
    "when the missing part turns up",
    "after checking the same place twice",
    "when I stop looking in the fridge",
    "after I check the fridge one more time",
    "when the dog is done barking",
    "after the cat allows it",
    "when the plant needs water again",
    "during the next full moon",
    "on a day ending in 'y'",
    "at some point between lunch and regret",
    "after the vibes improve",
    "when the timing is worse",
    "at the least convenient moment",
    "at exactly the wrong time",
    "when it would be funniest",
    "right after saying 'what could go wrong?'",
    "before anyone can stop me",
    "after everyone has left",
    "when the room gets quiet",
    "during the awkward pause",
    "after the conversation ends",
    "when the joke finally lands",
    "after the punchline",
    "once the embarrassment fades",
    "when I recover from this",
    "after a brief period of denial",
    "when the consequences arrive",
    "after the consequences are dealt with",
    "when the dust settles",
    "after the dust is vacuumed",
    "when the vacuum stops smelling weird",
    "once the situation is under control",
    "when the situation is no longer under control",
    "at an unspecified later date",
    "pending further information",
    "subject to change",
    "after further review",
    "when the schedule permits",
    "as soon as reasonably possible",
    "at the earliest convenience",
    "not during this calendar year",
    "eventually, probably",
    "later than planned",
    "earlier than expected",
    "right on schedule for once",
    "five minutes ago",
    "already",
    "a while ago",
    "before anyone asked",
    "after it was too late",
    "long after the point",
    "between then and now",
    "somewhere in the middle",
    "at an undisclosed time",
    "at a time yet to be determined",
    "when the clock stops being helpful",
    "whenever that is",
    "when it feels right",
    "when the timing is less bad",
    "not yet",
    "probably later",
    "maybe tomorrow",
    "ask me again in an hour",
    "check back next year",
    "call during business hours",
    "please allow three to five business days",
    "after a short delay",
    "after an unnecessarily long delay",
    "in the time it takes to regret sending that message",
    "when the batteries are replaced",
    "when the queue reaches the front",
    "when the last tab is closed",
    "after the group project is submitted",
    "when the boss stops typing",
    "after the meeting runs over",
    "when the Wi-Fi password is found",
    "once the leftovers are labeled",
    "when the mysterious noise stops",
    "after the smoke clears",
    "when the replacement arrives",
    "after the free trial ends",
    "when the subscription renews",
    "at the next minor inconvenience",
    "during the next avoidable crisis",
    "when someone says 'we need to talk'",
    "after the phrase 'long story short'",
    "at the exact moment I need to leave",
    "when there are no clean forks",
    "after the last clean shirt",
    "when the fridge light goes out",
    "once the line behind me gets longer",
    "after the cashier asks if I found everything",
    "when the self-checkout needs assistance again",
    "at closing time",
    "after closing time",
    "before opening time"
  ],
  "locations": [
    "the Grand Canyon",
    "a sex dungeon",
    "my sex dungeon",
    "the moon",
    "the Epstein island",
    "a gulag",
    "Big Ben",
    "Ireland",
    "the bottom of the Atlantic Ocean",
    "Ohio",
    "Deep Stone Crypt",
    "a Garfield comic",
    "Mystery Flesh Pit National Park, Texas",
    "Hell",
    "Heaven",
    "Purgatory",
    "Limbo (The outer border of Hell, not the game)",
    "Limbo (The game, not the outer border of Hell)",
    "de_dust2",
    "2Fort",
    "gm_construct",
    "Taco Bell:tm:",
    "Mcdonalds:tm:",
    "a strip club",
    "my basement",
    "a basement",
    "a haunted house",
    "my arms",
    "my arms, bridal style",
    "the Piss Drawer:tm:",
    "Northern Undead Asylum",
    "Anor Londo",
    "Firelink Shrine",
    "the cum sock",
    "Lavender Town",
    "Yharnam",
    "Blood Gulch",
    "Brazil",
    "the alley behind Tesco",
    "Gondor",
    "the New California Republic",
    "the New California Republic",
    "Kekistan",
    "Shangri-La",
    "Wakanda",
    "Duckburg",
    "Mos Eisley",
    "Castle Rock",
    "City 17",
    "Night City",
    "Raccoon City",
    "Skyrim",
    "Jame's bedroom",
    "the toilet",
    "the cum hamper",
    "the piss drawer",
    "my rectum",
    "your ear",
    "6 feet underground",
    "under AOC's feet",
    "Atlantis",
    "among the trees",
    "North Korea",
    "screaming from within the vomit coffin",
    "within Shaq's intercranial space",
    "flailing endlessly through innumerable, spontaneous cycles of death and rebirth",
    "within the fibers of Mario's mustache",
    "the bathroom at work",
    "the trough urinal at the baseball stadium",
    "ronald reagan's grave",
    "wakanda",
    "hogwarts",
    "times square",
    "the shire",
    "area 51",
    "raccoon city",
    "mount olympus",
    "silent hill",
    "the white house",
    "middle-earth",
    "narnia",
    "area 52",
    "the batcave",
    "atlantis",
    "disneyland",
    "springfield",
    "the death star",
    "gotham city",
    "las vegas",
    "tatooine",
    "alcatraz",
    "the upside down",
    "yellowstone",
    "mordor",
    "the grand canyon",
    "stars hollow",
    "the bermuda triangle",
    "rivendell",
    "area 51",
    "the hollywood sign",
    "themyscira",
    "pandora",
    "the sahara desert",
    "twin peaks",
    "metropolis",
    "neverland",
    "area 52",
    "the great pyramid",
    "the milky way",
    "king's landing",
    "area 53",
    "the eiffel tower",
    "the twilight zone",
    "area 54",
    "the mariana trench",
    "area 55",
    "the lost city of z",
    "area 56",
    "the x-files basement",
    "area 57",
    "night city",
    "the overlook hotel",
    "machu picchu",
    "rapture",
    "the great wall of china",
    "black mesa",
    "mount doom",
    "the colosseum",
    "arkham city",
    "the himalayas",
    "night vale",
    "the sydney opera house",
    "city 17",
    "the amazon rainforest",
    "twin peaks",
    "the golden gate bridge",
    "silent hill",
    "the statue of liberty",
    "derry",
    "the niagara falls",
    "lothlórien",
    "the taj mahal",
    "raccoon city",
    "the leaning tower of pisa",
    "the island (lost)",
    "the great barrier reef",
    "mos eisley",
    "the forbidden city",
    "silent hill",
    "mount rushmore",
    "the backrooms",
    "the eiffel tower",
    "jurassic park",
    "the grand budapest hotel",
    "the bermuda triangle",
    "the hollywood sign",
    "the misty mountains",
    "the white house",
    "the x-files basement",
    "the mariana trench",
    "the lost city of atlantis",
    "the shining's overlook hotel",
    "the great pyramid of giza",
    "the milky way",
    "the twilight zone",
    "the sahara desert",
    "the batcave",
    "the death star",
    "the citadel (half-life)",
    "the elder scrolls' tamriel",
    "paul cheenis' cheenis shack",
    "choose any 3 of your holes",
    "my lair",
    "my taint",
    "Israel",
    "Cedar Rapids",
    "toilet",
    "Peen Port",
    "Ton's house",
    "San Recto (a real place)",
    "Lincoln Memorial Reflecting Pool",
    "Pig Island",
    "the Yucatan Peninsula",
    "the weenie roast",
    "Upland, CA",
    "Whittier where the girls are prettier <:perish:507772507139604511>",
    "Pee Pee Palace",
    "Greenville, SC",
    "there",
    "a laundromat at 2 a.m.",
    "the DMV",
    "a nearly empty airport terminal",
    "the back room of a furniture store",
    "a roadside diner",
    "the top floor of a parking garage",
    "a public library",
    "the frozen food aisle",
    "a hotel conference room",
    "the lost-and-found office",
    "a bus station",
    "the nearest Costco",
    "a bowling alley",
    "an abandoned shopping mall",
    "the food court",
    "a dentist's waiting room",
    "the employee entrance",
    "a storage unit",
    "the parking lot behind a movie theater",
    "a rest stop off the highway",
    "the local aquarium",
    "a county fair",
    "the back of a rideshare",
    "a truck stop",
    "a community college parking lot",
    "the mall fountain",
    "a self-storage facility",
    "a closed-down video store",
    "the airport baggage claim",
    "a grocery store break room",
    "the roof of a Waffle House",
    "a public swimming pool",
    "the line at the post office",
    "a motel room with one working lamp",
    "a suburban cul-de-sac",
    "the nearest escape room",
    "a pawn shop",
    "the basement of a church",
    "a local car wash",
    "the back seat of a taxi",
    "a pet store",
    "the hallway outside a courthouse",
    "a suspiciously empty restaurant",
    "a 24-hour pharmacy",
    "the loading dock behind a supermarket",
    "a high school gymnasium",
    "the world's least busy Starbucks",
    "a public park after dark",
    "the smoking area outside a casino",
    "a county records office",
    "the last booth at Denny's",
    "a wedding venue during setup",
    "the maintenance tunnel beneath a stadium",
    "an ice rink lobby",
    "the local historical society",
    "a warehouse full of office chairs",
    "the wrong terminal at the airport",
    "a roadside fruit stand",
    "a mall kiosk selling phone cases",
    "the back of a moving truck",
    "a nearly empty movie theater",
    "the city bus depot",
    "a hotel laundry room",
    "a quiet corner of IKEA",
    "a closed museum exhibit",
    "the parking lot of a closed restaurant",
    "a municipal water treatment plant",
    "the office of a tax preparer",
    "a forgotten train platform",
    "the customer service desk",
    "a public access television studio",
    "the roof of a strip mall",
    "a small-town newspaper office",
    "the basement of a bowling alley",
    "a roadside motel",
    "the wrong side of the river",
    "a convention center hallway",
    "an empty school bus",
    "the local historical battlefield",
    "a dentist's supply closet",
    "the back of a hardware store",
    "a shopping cart return area",
    "a hotel vending machine alcove",
    "the employee parking lot",
    "a public restroom with no soap",
    "the lobby of an office building",
    "a car dealership after closing",
    "the town's only karaoke bar",
    "a marina parking lot",
    "the last table at a buffet",
    "a warehouse district",
    "a closed amusement park",
    "the local courthouse steps",
    "a train crossing",
    "a community theater backstage",
    "the basement of a library",
    "a nearly empty sports bar",
    "the pet food aisle",
    "an airport parking shuttle",
    "a public golf course",
    "a mall security office",
    "the back of a bakery",
    "a vending machine repair shop",
    "the lobby of a budget motel",
    "a suburban storm drain",
    "the parking garage stairwell",
    "a highway median",
    "the waiting area at an auto shop",
    "a closed bank branch",
    "the town's oldest bar",
    "a farmer's market after closing",
    "the side entrance of a hospital",
    "a water park in the off-season",
    "a public tennis court",
    "a university lecture hall",
    "the campus parking structure",
    "a record store basement",
    "the back aisle of a thrift store",
    "a vacant storefront",
    "the lobby of a courthouse",
    "a fast-food restaurant's play area",
    "a marina bathroom",
    "a forgotten office kitchenette",
    "the service elevator",
    "a parking lot full of shopping carts",
    "a bus shelter in the rain",
    "the local recycling center",
    "a roadside antique shop",
    "the back row of a church",
    "a hotel room between guests",
    "the break room at a call center",
    "an empty convention hall",
    "the corner booth at a diner",
    "a storage closet under the stairs",
    "a train station restroom",
    "the basement of a community center",
    "a deserted outlet mall",
    "the line for airport security",
    "a public pier",
    "the office behind a dry cleaner",
    "a university vending machine area",
    "the back room of a pharmacy",
    "a parking lot during a fire drill",
    "the local recycling bin",
    "a hallway with no signs",
    "the last open business in town",
    "the third floor of an abandoned office building",
    "the place where the missing socks go",
    "the wrong exit off the freeway",
    "the empty seat at the meeting",
    "a room marked 'authorized personnel only'",
    "the end of a dead-end street",
    "a waiting room from another decade",
    "the nearest place with free Wi-Fi",
    "the town's unofficial meeting spot",
    "the back of the line",
    "the place you were supposed to be five minutes ago",
    "somewhere across town",
    "the middle of nowhere",
    "the other side of town",
    "a place nobody thought to check",
    "the nearest open bathroom",
    "a location pending confirmation"
  ],
  "reasons": [
    "said the earth is flat",
    "has a girthy balloon shlong",
    "h",
    "stinky",
    "said chemtrails are turning people gay",
    "Epstein didn't kill himself",
    "be shoppin",
    "is coming to town",
    "is watching you",
    "happens for a reason",
    "doesn't care about black people",
    "benefits the military-industrial complex",
    "has never had a dream",
    "isn't real",
    "thinks 2pac is still alive",
    "'s anus is bleeding",
    "has been farting alone in flaccid chat for 6 hours",
    "said it in secret chat",
    "ate the burger king foot lettuce",
    "is going to kick your ass, and i'm going to help him",
    "is a lizard",
    "forgot the question",
    "is an alcoholic",
    "wills it to be so.",
    "profited off the Iraq war",
    "opinions only get worse",
    "says GHIF",
    "is COOOOOOOOOOOMING",
    "is a :clown:",
    "going to lose subscriber",
    "told malarkey",
    ", dey suffer",
    "hates white pipo",
    "is SO BEEFY!!",
    "killed hooters",
    "dont trust you :sob:",
    "is in love with the coco :weary:",
    "didn't hit that MF LIKE AND SUBSCRIBE BUTTON",
    "said poopie is funny",
    "said UH OH, stinky",
    "rotted",
    "is a figment of your imagination",
    "is once again asking you to shut the fuck up",
    "is ignoring your pings",
    "SUKA BLYAT",
    "is a TABLE",
    "hardly knows her!",
    "can't read",
    "shidded",
    "has a smol pebis",
    "is cooming",
    "has abandoned us",
    "calls it oven when you of in the cold food of out hot eat the food",
    "has a salty six inch that isn't big enough for the both of us",
    "is the king of being wrong",
    "decreed it",
    "does not rove da rord",
    "never reveals her age",
    "can has cheesburger",
    "once said 7 eleven hot dogs aren't that bad",
    "thinks taco bell is mexican food",
    "thinks del taco is better than taco bell",
    "thinks ketchup doesn't belong on eggs",
    "bought another iPhone",
    "is the reason rotisserie chicken from albertsons is so cheap...",
    "says italian food is better than any other food",
    "has a perfect fat pussy",
    "went to five or six stores instead of just one",
    "is afraid to leave his stoop",
    "is a republican",
    "joined a pyramid scheme",
    "shouldn't be allowed to vote",
    "said squirt is pee",
    "`shidded and farded and cummed`",
    "INVENTED BEANS",
    "is stored in the ass",
    "is stored in the balls",
    "deleted it because they did not like it",
    "is stored in the soul",
    "never returned backdoor sluts 4 to blockbuster :flushed:",
    "because la habra 300 bowl is",
    "doesn't wash their ass",
    "is a registered sex offender in 38 states",
    "leg so hot it fry an eg",
    "slings a fat hog",
    "peed in the sink",
    "has a worryingly skinny pussy",
    "has coronavirus",
    "went tits up in the stock market",
    "was left off bad n boujee",
    "got its lime :beers:",
    "needs kammies",
    "is a masochist",
    "has gone mental, absolutely bonkers",
    "never really loved you anyway",
    "is secretly an alt-right youtuber with a cartoon animal avatar in a suit",
    "wants to wear your skin",
    "smells like gun-girl's undies",
    "is locked in an ICE internment center",
    "doesn't care about black people",
    "need drinky",
    "is a fuckcrustable",
    "is a massive fucktardian cunt waffle of epic proportions",
    "got a tutorial from jeff",
    "has dementia",
    "forgot to",
    "has died",
    "worships satan",
    "has 3 nipples",
    "smells like shit",
    "drank redbull and didn't get wings",
    "really needs a sorking",
    "cums first",
    "wasn't invited to the Roman orgy",
    "is off his rocker, innit?",
    "has nipple piercings",
    "creamed in the trash",
    "do kinda be vibin tho",
    "is tokin n strokin, bruv",
    "did black face 10 years ago",
    "smokes cigarettes without the filters",
    "confused ham for string beans",
    "was made deaf by space",
    "ate bad noodle",
    "thinks green beans belong on pizza",
    "sniffs cocks",
    "pood and pidded",
    "came in the shower",
    "farted at work",
    "hates minorities",
    "is too beautiful for this earth",
    "is a binch",
    "sucks",
    "tried to fart but accidentally shit",
    "once slapped a nun",
    "is a ghost",
    "prefers boned wings",
    "is a degenerate",
    "is wanted by INTERPOL",
    "shits standing up",
    "is an undercover FBI agent",
    "doesnt wipe",
    "hides snacks in their foreskin",
    "has ashy skin",
    "has no teeth",
    "invented green bean pizza",
    "draws furries for a living",
    "yiffs in their free time",
    "is secretly a chud",
    "loves the pungent copypasta",
    "types with two fingers",
    "goes to sink-pissers anonymous",
    "is addicted to crack",
    "is addicted to their own farts",
    "is a nice person, actually",
    "eats with their mouth open",
    "microwaves cat food in the office",
    "thinks the earth is flat",
    "is an antivaxxer",
    "is in a coma. wake up please!",
    "is illegal",
    "only wipes if people are watching",
    "is the reason there is always piss on the toilet seat",
    "clogged the toilet",
    "is the zodiac killer",
    "wishes they could feel pain",
    "has diarrhea",
    "is gassy",
    "is a bigg dummy",
    "has a sex tape",
    "is ben shapiro's wife",
    "sucks eggs",
    "walks too slowly in public",
    "is Q",
    "crop dusted some old guy reading the paper",
    "shouldn't have trusted that fart",
    "flew to cancun",
    "is le epic redditor extraordinaire mlady",
    "eats kool aid pickles",
    "denies the holocaust",
    "is the imposter",
    "is lookin pretty sus ngl",
    "is amogus",
    "has night vision",
    "isn't allowed to fart",
    "will NOT be coming back to this establishment",
    "spilled the cum jar",
    "cannot be arsed to care",
    "is a serial killer",
    "is stinky",
    "is your real dad",
    "is cursed to edge for eternity",
    "is blasting rope",
    "just blasted rope",
    "shidded they pant and underwear also",
    "cried when henry kissinger died",
    "love scat porn",
    "is secretly a Rothschild",
    "is freaky, they're horny",
    "lost the salami lid",
    "isn't here",
    "I KNOW they ate a cheese",
    "is off the drankies",
    "has a Brian Griffin tattoo",
    "needs to spread their spore",
    "got caught looksmaxxing",
    "they fucking love peanut butter",
    "they fucking love science! 🤪",
    "of WOKE",
    "allah willed it to be so",
    "i'm spooky",
    "HEEEELP!! HELP MEE!!!! THIS IS NOT A JOKE HELP!!!!!",
    "I’m freaky!",
    "I’m freaky! I'm horny!",
    "is shit thumping and pisspilling",
    "losing subscriber!",
    "sun downing in the club",
    "you're a geek",
    "went rotten an hour ago",
    "are putting a hole in their house",
    "i FUCK the fish",
    "only drank 99 beers in a month",
    "the Bible tells me so",
    "that's how mafia works",
    "got their teeth lasered clean off",
    "couldn’t maintain an erection, but he could cum",
    "clown event still possible",
    "needs... tickling",
    "is getting killed and sucked off later",
    "ordered cheap shoes off Ebay",
    "they died in a tragic self-suck attempt gone wrong",
    "dropped a generational brown in the ralph's bathroom",
    "they **succ**eeded in a glorious self-suck attempt and should be commended",
    "nuts way too big",
    "couldn't decide which toilet to use so they shat their pants",
    "shat their pants",
    "pissed in their socks",
    "moon's haunted",
    "uses arch btw",
    "is squids road",
    "is having a wet beef",
    "you do not dare to cream",
    "they creamed too much",
    "mom found the poop sock",
    "didn't wash their ass today",
    "doesn't believe in germs",
    "he’s cock is green",
    "is eating shit from a butt with a side of poop from an ass",
    "awakened 1000 years of liberal darkness",
    "is jorking it pork style",
    "spilled hot coffee on their right nut",
    "is listening to Damn by Kendrick Lamar",
    "descended into madness",
    "we carry the flame",
    "is vitamin D deficient",
    "BROKE his pussy",
    "got they MEAT ROCKED UP",
    "smokin a skinny winny",
    "HIT THE JUCKPORT 1 TRILLION $",
    "bloody fuck you bloody!",
    "is a boomer that got mogged by my youthful stride",
    "was touched by pestilence",
    "detached her pussy",
    "these frenzied codgers are jacking off—and they're jacking off hard",
    "took 10 greasy lessons",
    "a grinch stole their inch",
    "my thinking is too cross-domain and voluminous",
    "pooped their butt",
    "is watching Blacked… on Christmas Day",
    "IM IN LOVE WITH THE COCO",
    "is watching keys jingle",
    "funy",
    "don't worry about it, kitten",
    "you're a loser!",
    "I love you 😊",
    "9/11",
    "is too horny to die",
    "is in no hurry",
    "didn't consider the syntax",
    "revolution, like urine, must be aimed with purpose",
    "had something chinese happen to them",
    "really sees their caca",
    "loves refrigerators",
    "is entombed in my big round belly, yummy!",
    "hit the juckport 1 trillion$",
    "aint never had no chia pet pussy",
    "the homeboys like weiner",
    "loved their mother unlike you ungrateful piece of shit",
    "took the ipad away from horny mexican yoda",
    "gnunged",
    "returned the slab and avoided the curse",
    "failed to return the slab, and therefore is currently suffering from King Ramses' Curse",
    "jarred dehydrated Mexican Yoda in a mason jar of vinegar",
    "invited darkness into their heart",
    "died in some fiery explosion",
    "sucked the wrong dick 😔",
    "has a beautiful soul",
    "went Evil Mode",
    "went gleeful and yippee maxed",
    "likes drugs",
    "ate too much fiber",
    "overdosed on Flintstones vitamins and is now invincible",
    "son 😭",
    "they're six feet from the edge and they're thinking \"maybe six feet aint so far down\"",
    "is ghoulmaxxing",
    "they don't give a fuck homie"
  ],
  "sizes": [
    "large",
    "small",
    "medium",
    "puny",
    "gigantic",
    "average",
    "incongruous",
    "nice :thumbsup:",
    ":b:ig",
    "immense",
    "voluptuous",
    "h",
    "bigger than I'd like :/",
    "smaller than I'd like :/",
    "vast",
    "globular",
    "eternal",
    "*just right*",
    "normal",
    "¡Sabado Gigante!",
    "narrow",
    "wide",
    "petite",
    "insignificant",
    "short",
    "0.127 mm",
    ":ok:",
    "smallish",
    "XXL",
    "XXS",
    "big-boned",
    "king size",
    "FAT",
    "mediocre",
    "unexceptional",
    "immeasurable",
    "trivial",
    "intermediate",
    "passable",
    "regular",
    "tainted",
    "common",
    "12 inches",
    "1 foot",
    "5 & 1/2 centimeters",
    "futuristic",
    "macho",
    "4 yards",
    "2 meters",
    ":fire::100::fire::100::fire::100:",
    "thicc",
    "microscopic",
    "gargantuan",
    ":flushed:",
    "assertive",
    "reptilian",
    "ghastly",
    "delightful",
    "debonair",
    "homely",
    "nonexistent",
    "left: 15cm, right: 1cm",
    "1mm",
    "1 in.",
    "3cm",
    "about that of a golf ball",
    "Epstein didn't kill himself",
    "too big to handle",
    "just right",
    "ordinary",
    "unwieldy",
    "embarrassing",
    "cubic",
    "shriveled",
    "that of a BEAN",
    "six of one, half dozen of the other",
    "an acre",
    "US Men's 11",
    "UK Women's 7 & 1/2",
    "a lima bean",
    "unusual",
    "gamer sized :video_game:",
    "amassed",
    "in South Carolina until 10/12",
    "husky",
    "big and tall",
    "fine",
    "sizeable",
    "beach ball",
    ":chart_with_upwards_trend:",
    ":chart_with_downwards_trend:",
    "boomer-sized",
    "minute",
    "old-fashioned",
    "frail",
    "nutty",
    "broad",
    "crooked",
    "euclidean",
    "obtuse",
    "portable",
    "stubby",
    "insufficient",
    "plump",
    "corn-fed",
    "flabby",
    "opulent",
    "liberal",
    "confusing",
    "questionable",
    "lacking self-confidence",
    "uncertain",
    "meager",
    "lacking quality",
    "free",
    "enslaved",
    "distinguished",
    "vegan",
    "poignant",
    "special 🙂",
    "enticing <:bites_lip:813835068904701972>",
    "2gb",
    "freaky",
    "creepy",
    "wet",
    "the size of the smallest in n out yellow chili youve ever seen",
    "wimpy",
    "potato-like",
    "confused",
    "abrasive",
    "awesome",
    "grapefruit",
    "n't what matters. its what's inside them that counts",
    "porked",
    "catastrophic",
    "noir",
    "with pulp"
  ],
  "allEmoji": [
    "🅰️",
    "🅱️",
    "🅾️",
    "🅿️",
    "🆎",
    "🆑",
    "🆒",
    "🆓",
    "🆔",
    "🆕",
    "🆖",
    "🆗",
    "🆘",
    "🆙",
    "🌂",
    "🌃",
    "🌄",
    "🌅",
    "🌆",
    "🌇",
    "🌈",
    "🌉",
    "🌊",
    "🌋",
    "🌌",
    "🌍",
    "🌐",
    "🌑",
    "🌒",
    "🌕",
    "🌙",
    "🌚",
    "🌛",
    "🌜",
    "🌝",
    "🌞",
    "🌟",
    "🌠",
    "🌡️",
    "🌤️",
    "🌥️",
    "🌦️",
    "🌧️",
    "🌨️",
    "🌩️",
    "🌪️",
    "🌫️",
    "🌬️",
    "🌭",
    "🌮",
    "🌯",
    "🌰",
    "🌱",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🌶️",
    "🌷",
    "🌸",
    "🌹",
    "🌺",
    "🌻",
    "🌼",
    "🌽",
    "🌾",
    "🌿",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🍄",
    "🍅",
    "🍆",
    "🍇",
    "🍈",
    "🍉",
    "🍊",
    "🍋",
    "🍌",
    "🍍",
    "🍎",
    "🍏",
    "🍐",
    "🍑",
    "🍒",
    "🍓",
    "🍔",
    "🍕",
    "🍖",
    "🍗",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍞",
    "🍟",
    "🍠",
    "🍡",
    "🍢",
    "🍣",
    "🍤",
    "🍥",
    "🍦",
    "🍧",
    "🍨",
    "🍩",
    "🍪",
    "🍫",
    "🍬",
    "🍭",
    "🍮",
    "🍯",
    "🍰",
    "🍱",
    "🍲",
    "🍳",
    "🍴",
    "🍵",
    "🍶",
    "🍷",
    "🍸",
    "🍹",
    "🍺",
    "🍻",
    "🍼",
    "🍽️",
    "🍾",
    "🍿",
    "🎀",
    "🎁",
    "🎂",
    "🎃",
    "🎄",
    "🎅",
    "🎆",
    "🎇",
    "🎈",
    "🎉",
    "🎊",
    "🎋",
    "🎌",
    "🎍",
    "🎎",
    "🎏",
    "🎐",
    "🎑",
    "🎒",
    "🎓",
    "🎖️",
    "🎗️",
    "🎙️",
    "🎚️",
    "🎛️",
    "🎞️",
    "🎟️",
    "🎠",
    "🎡",
    "🎢",
    "🎣",
    "🎤",
    "🎥",
    "🎦",
    "🎧",
    "🎨",
    "🎩",
    "🎪",
    "🎫",
    "🎬",
    "🎭",
    "🎮",
    "🎯",
    "🎰",
    "🎱",
    "🎲",
    "🎳",
    "🎴",
    "🎵",
    "🎶",
    "🎷",
    "🎸",
    "🎹",
    "🎺",
    "🎻",
    "🎼",
    "🎽",
    "🎾",
    "🎿",
    "🏀",
    "🏁",
    "🏌️",
    "🏍️",
    "🏎️",
    "🏏",
    "🏐",
    "🏑",
    "🏒",
    "🏓",
    "🏔️",
    "🏕️",
    "🏖️",
    "🏗️",
    "🏘️",
    "🏙️",
    "🏚️",
    "🏛️",
    "🏜️",
    "🏝️",
    "🏞️",
    "🏟️",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏧",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏮",
    "🏯",
    "🏰",
    "🏳️‍🌈",
    "🏴",
    "🏵️",
    "🏷️",
    "🏸",
    "🏹",
    "🏺",
    "🐀",
    "🐈",
    "🐉",
    "🐊",
    "🐋",
    "🐌",
    "🐍",
    "🐎",
    "🐏",
    "🐐",
    "🐑",
    "🐒",
    "🐓",
    "🐔",
    "🐕‍🦺",
    "🐕",
    "🐖",
    "🐗",
    "🐘",
    "🐙",
    "🐚",
    "🐛",
    "🐜",
    "🐝",
    "🐞",
    "🐟",
    "🐠",
    "🐡",
    "🐢",
    "🐣",
    "🐤",
    "🐥",
    "🐦",
    "🐧",
    "🐨",
    "🐩",
    "🐪",
    "🐫",
    "🐬",
    "🐭",
    "🐮",
    "🐯",
    "🐰",
    "🐱",
    "🐲",
    "🐳",
    "🐴",
    "🐵",
    "🐶",
    "🐷",
    "🐸",
    "🐹",
    "🐺",
    "🐻",
    "🐼",
    "🐽",
    "🐾",
    "🐿️",
    "👀",
    "👁‍🗨",
    "👁️",
    "👃",
    "👄",
    "👅",
    "👆",
    "👈",
    "👋",
    "👌",
    "👍",
    "👏",
    "👐",
    "👑",
    "👒",
    "👓",
    "👔",
    "👕",
    "👖",
    "👗",
    "👘",
    "👙",
    "👚",
    "👛",
    "👜",
    "👝",
    "👞",
    "👟",
    "👠",
    "👡",
    "👢",
    "👣",
    "👤",
    "👥",
    "👹",
    "👺",
    "👻",
    "👼",
    "👽",
    "👾",
    "👿",
    "💀",
    "💃",
    "💄",
    "💅",
    "💆",
    "💇‍♀️",
    "💇‍♂️",
    "💇",
    "💈",
    "💉",
    "💊",
    "💋",
    "💌",
    "💍",
    "💎",
    "💏",
    "💐",
    "💑",
    "💒",
    "💓",
    "💔",
    "💕",
    "💖",
    "💗",
    "💘",
    "💙",
    "💚",
    "💛",
    "💜",
    "💝",
    "💞",
    "💟",
    "💠",
    "💡",
    "💢",
    "💣",
    "💤",
    "💥",
    "💦",
    "💧",
    "💨",
    "💩",
    "💪",
    "💫",
    "💬",
    "💭",
    "💮",
    "💯",
    "💰",
    "💱",
    "💲",
    "💳",
    "💴",
    "💵",
    "💶",
    "💷",
    "💸",
    "💹",
    "💺",
    "💻",
    "💼",
    "💽",
    "💾",
    "💿",
    "📀",
    "📁",
    "📂",
    "📃",
    "📄",
    "📅",
    "📆",
    "📇",
    "📈",
    "📉",
    "📊",
    "📋",
    "📌",
    "📍",
    "📎",
    "📏",
    "📐",
    "📑",
    "📒",
    "📓",
    "📔",
    "📕",
    "📖",
    "📗",
    "📘",
    "📙",
    "📚",
    "📛",
    "📜",
    "📝",
    "📞",
    "📟",
    "📠",
    "📡",
    "📢",
    "📣",
    "📤",
    "📥",
    "📦",
    "📧",
    "📨",
    "📩",
    "📪",
    "📫",
    "📬",
    "📭",
    "📮",
    "📯",
    "📰",
    "📱",
    "📲",
    "📳",
    "📴",
    "📵",
    "📶",
    "📷",
    "📸",
    "📹",
    "📺",
    "📻",
    "📼",
    "📽️",
    "📿",
    "🔀",
    "🔁",
    "🔂",
    "🔃",
    "🔄",
    "🔅",
    "🔆",
    "🔇",
    "🔈",
    "🔉",
    "🔊",
    "🔋",
    "🔌",
    "🔍",
    "🔎",
    "🔏",
    "🔐",
    "🔑",
    "🔒",
    "🔓",
    "🔔",
    "🔕",
    "🔖",
    "🔗",
    "🔘",
    "🔙",
    "🔚",
    "🔛",
    "🔜",
    "🔝",
    "🔞",
    "🔟",
    "🔠",
    "🔡",
    "🔢",
    "🔣",
    "🔤",
    "🔥",
    "🔦",
    "🔧",
    "🔨",
    "🔩",
    "🔪",
    "🔫",
    "🔬",
    "🔭",
    "🔮",
    "🔯",
    "🔰",
    "🔱",
    "🔲",
    "🔳",
    "🔴",
    "🔵",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "🔼",
    "🔽",
    "🕉️",
    "🕊️",
    "🕋",
    "🕌",
    "🕍",
    "🕎",
    "🕐",
    "🕯️",
    "🕰️",
    "🕵️‍♀️",
    "🕵️‍♂️",
    "🕵️",
    "🕶️",
    "🕷️",
    "🕸️",
    "🕺",
    "🖇️",
    "🖐️",
    "🖤",
    "🖥️",
    "🖨️",
    "🖱️",
    "🖲️",
    "🖼️",
    "🗂️",
    "🗃️",
    "🗄️",
    "🗑️",
    "🗒️",
    "🗓️",
    "🗜️",
    "🗝️",
    "🗞️",
    "🗡️",
    "🗣️",
    "🗨️",
    "🗯️",
    "🗳️",
    "🗺️",
    "🗻",
    "🗼",
    "🗽",
    "🗾",
    "🗿",
    "😀",
    "😁",
    "😂",
    "😃",
    "😄",
    "😅",
    "😆",
    "😇",
    "😈",
    "😉",
    "😊",
    "😋",
    "😌",
    "😍",
    "😎",
    "😏",
    "😐",
    "😑",
    "😒",
    "😓",
    "😔",
    "😕",
    "😖",
    "😗",
    "😘",
    "😙",
    "😚",
    "😛",
    "😜",
    "😝",
    "😞",
    "😟",
    "😠",
    "😡",
    "😢",
    "😣",
    "😤",
    "😥",
    "😦",
    "😧",
    "😨",
    "😩",
    "😪",
    "😫",
    "😬",
    "😭",
    "😮",
    "😯",
    "😰",
    "😱",
    "😲",
    "😳",
    "😴",
    "😵",
    "😶",
    "😷",
    "😸",
    "😹",
    "😺",
    "😻",
    "😼",
    "😽",
    "😾",
    "😿",
    "🙀",
    "🙁",
    "🙂",
    "🙃",
    "🙄",
    "🙅‍♀️",
    "🙅‍♂️",
    "🙅",
    "🙆‍♀️",
    "🙆‍♂️",
    "🙆",
    "🙇‍♀️",
    "🙇‍♂️",
    "🙇",
    "🙈",
    "🙉",
    "🙊",
    "🙋‍♀️",
    "🙋‍♂️",
    "🙋",
    "🙌",
    "🙍‍♀️",
    "🙍‍♂️",
    "🙍",
    "🙎‍♀️",
    "🙎‍♂️",
    "🙎",
    "🙏",
    "🚀",
    "🚁",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚋",
    "🚌",
    "🚍",
    "🚎",
    "🚏",
    "🚐",
    "🚑",
    "🚒",
    "🚓",
    "🚔",
    "🚕",
    "🚖",
    "🚗",
    "🚘",
    "🚙",
    "🚚",
    "🚛",
    "🚜",
    "🚝",
    "🚞",
    "🚟",
    "🚠",
    "🚡",
    "🚢",
    "🚣",
    "🚤",
    "🚥",
    "🚦",
    "🚧",
    "🚨",
    "🚩",
    "🚪",
    "🚫",
    "🚬",
    "🚭",
    "🚮",
    "🚯",
    "🚰",
    "🚱",
    "🚲",
    "🚳",
    "🚵‍♀️",
    "🚵‍♂️",
    "🚵",
    "🚶‍♀️",
    "🚶‍♂️",
    "🚶",
    "🚷",
    "🚸",
    "🚹",
    "🚺",
    "🚻",
    "🚼",
    "🚽",
    "🚾",
    "🚿",
    "🛀",
    "🛁",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "🛌",
    "🛍️",
    "🛎️",
    "🛏️",
    "🛐",
    "🛑",
    "🛒",
    "🛕",
    "🛠️",
    "🛡️",
    "🛢️",
    "🛣️",
    "🛤️",
    "🛥️",
    "🛩️",
    "🛫",
    "🛬",
    "🛰️",
    "🛳️",
    "🛴",
    "🛵",
    "🛶",
    "🛷",
    "🛸",
    "🛹",
    "🛺",
    "🛻",
    "🛼",
    "🟠",
    "🟡",
    "🟢",
    "🟣",
    "🟤",
    "🟥",
    "🟦",
    "🟧",
    "🟨",
    "🟩",
    "🟪",
    "🟫",
    "🤍",
    "🤏",
    "🤐",
    "🤑",
    "🤒",
    "🤓",
    "🤔",
    "🤕",
    "🤖",
    "🤗",
    "🤘",
    "🤙",
    "🤚",
    "🤛",
    "🤝",
    "🤞",
    "🤟",
    "🤠",
    "🤡",
    "🤢",
    "🤣",
    "🤤",
    "🤥",
    "🤦‍♀️",
    "🤦‍♂️",
    "🤦",
    "🤧",
    "🤨",
    "🤩",
    "🤪",
    "🤫",
    "🤬",
    "🤭",
    "🤮",
    "🤯",
    "🤿",
    "🥀",
    "🥁",
    "🥂",
    "🥃",
    "🥄",
    "🥅",
    "🥇",
    "🥈",
    "🥉",
    "🥊",
    "🥋",
    "🥌",
    "🥍",
    "🥎",
    "🥏",
    "🥐",
    "🥑",
    "🥒",
    "🥓",
    "🥔",
    "🥕",
    "🥖",
    "🥗",
    "🥘",
    "🥙",
    "🥚",
    "🥛",
    "🥜",
    "🥝",
    "🥞",
    "🥟",
    "🥠",
    "🥡",
    "🥢",
    "🥣",
    "🥤",
    "🥥",
    "🥦",
    "🥧",
    "🥨",
    "🥩",
    "🥪",
    "🥫",
    "🥬",
    "🥭",
    "🥮",
    "🥯",
    "🥰",
    "🥱",
    "🥲",
    "🥳",
    "🥴",
    "🥵",
    "🥶",
    "🧑",
    "🧕",
    "🧚",
    "🧜‍♀️",
    "🧝‍♀️",
    "🧝‍♂️",
    "🧝",
    "🧞‍♀️",
    "🧞‍♂️",
    "🧞",
    "🧟‍♀️",
    "🧠",
    "🧡",
    "🧢",
    "🧣",
    "🧤",
    "🧥",
    "🧦",
    "🧧",
    "🧨",
    "🧩",
    "🧪",
    "🧫",
    "🧬",
    "🧭",
    "🧮",
    "🧯",
    "🧰",
    "🧱",
    "🧲",
    "🧳",
    "🧴",
    "🧵",
    "🧶",
    "🧷",
    "🧸",
    "🧹",
    "🧺",
    "🧻",
    "🧼",
    "🧽",
    "🧾",
    "🧿",
    "🩰",
    "🩱",
    "🩲",
    "🩳",
    "🩴",
    "🩸",
    "🩹",
    "🩺",
    "🪀",
    "🪁",
    "🪂",
    "🪐",
    "🪑",
    "🪒",
    "🪓",
    "🪔",
    "‼️",
    "⁉️",
    "™️",
    "ℹ️",
    "↔️",
    "⏰",
    "⏱️",
    "⏲️",
    "⏳",
    "☀️",
    "☁️",
    "☂️",
    "☃️",
    "☄️",
    "☎️",
    "☑️",
    "☔️",
    "☕️",
    "☘️",
    "☝️",
    "☠️",
    "☢️",
    "☣️",
    "☦️",
    "☪️",
    "☮️",
    "☯️",
    "☸️",
    "☹️",
    "☺️",
    "♀️",
    "♂️",
    "♟️",
    "♠️",
    "♣️",
    "♥️",
    "♦️",
    "♨️",
    "♻️",
    "♾",
    "♿️",
    "⚒️",
    "⚓️",
    "⚔️",
    "⚕️",
    "⚖️",
    "⚗️",
    "⚙️",
    "⚛️",
    "⚜️",
    "⚠️",
    "⚡️",
    "⚧️",
    "⚪️",
    "⚫️",
    "⚰️",
    "⚱️",
    "⚽️",
    "⚾️",
    "⛄️",
    "⛅️",
    "⛈️",
    "⛏️",
    "⛑️",
    "⛓️",
    "⛔️",
    "⛰️",
    "⛱️",
    "⛳️",
    "⛴️",
    "⛷️",
    "⛺️",
    "✂️",
    "✅",
    "✈️",
    "✉️",
    "✊",
    "✋",
    "✌️",
    "✍️",
    "✏️",
    "✒️",
    "✔️",
    "✖️",
    "✝️",
    "✡️",
    "✨",
    "✳️",
    "✴️",
    "❄️",
    "❇️",
    "❌",
    "❎",
    "❓",
    "❗️",
    "❣️",
    "❤️",
    "➕",
    "➖",
    "➗",
    "➡️",
    "➰",
    "➿",
    "⤴️",
    "⤵️",
    "*⃣",
    "⬅️",
    "⬆️",
    "⬇️",
    "⬛️",
    "⬜️",
    "⭕️"
  ],
  "wtf": "What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.",
  "cummies": "Just me and my :two_hearts:daddy:two_hearts:, hanging out I got pretty hungry:eggplant: so I started to pout :disappointed: He asked if I was down :arrow_down:for something yummy :heart_eyes::eggplant: and I asked what and he said he'd give me his :sweat_drops:cummies!:sweat_drops: Yeah! Yeah!:two_hearts::sweat_drops: I drink them!:sweat_drops: I slurp them!:sweat_drops: I swallow them whole:sweat_drops: :heart_eyes: It makes :cupid:daddy:cupid: :blush:happy:blush: so it's my only goal... :two_hearts::sweat_drops::tired_face:Harder daddy! Harder daddy! :tired_face::sweat_drops::two_hearts: 1 cummy:sweat_drops:, 2 cummy:sweat_drops::sweat_drops:, 3 cummy:sweat_drops::sweat_drops::sweat_drops:, 4:sweat_drops::sweat_drops::sweat_drops::sweat_drops: I'm :cupid:daddy's:cupid: :crown:princess :crown:but I'm also a whore! :heart_decoration: He makes me feel squishy:heartpulse:!He makes me feel good:purple_heart:! :cupid::cupid::cupid:He makes me feel everything a little kitten should!~ :cupid::cupid::cupid: :crown::sweat_drops::cupid:Wa-What!:cupid::sweat_drops::crown:",
  "syllables": [
    "eu",
    "xeu",
    "bu",
    "lem",
    "lum",
    "hue",
    "shaq",
    "anus",
    "cumb",
    "yeff",
    "bort",
    "dort",
    "toe",
    "geep",
    "doop",
    "glurp",
    "gleep",
    "mlem",
    "crunt",
    "smeg",
    "bloop",
    "sork",
    "creen",
    "grelp",
    "spug",
    "grench",
    "soop",
    "linp",
    "clonk",
    "quorp",
    "jink",
    "twonk",
    "glump",
    "hurg",
    "dorf",
    "sorp",
    "gorp",
    "lump",
    "dink",
    "clump",
    "gert",
    "bum",
    "slunt",
    "chunt",
    "gus",
    "grun",
    "glum",
    "clop",
    "spuhg",
    "garg",
    "gru",
    "plo",
    "goug",
    "gerg",
    "gor",
    "gee",
    "gerp",
    "grub",
    "blip",
    "blop",
    "trig",
    "ronk",
    "borg",
    "fart",
    "goo",
    "chud",
    "zab",
    "zom",
    "zub",
    "jun",
    "jor",
    "jer",
    "pul",
    "pow",
    "gum",
    "cum",
    "pee",
    "piss",
    "shit",
    "butt",
    "sprat",
    "pomp",
    "gup",
    "gur",
    "gel",
    "pol",
    "dob",
    "bop",
    "chup",
    "slob",
    "glob",
    "blob",
    "wob",
    "bob",
    "gob",
    "tumb",
    "bumb",
    "wumb",
    "rump",
    "gump",
    "goob",
    "milk",
    "gilf",
    "milf",
    "dilf",
    "pilk",
    "rod",
    "god",
    "sod",
    "bud",
    "stick",
    "sud",
    "suck",
    "fuck",
    "cunt",
    "puss",
    "cock",
    "sock",
    "bock",
    "bink",
    "gog",
    "Obama",
    "berk",
    "dirk",
    "sump",
    "fug",
    "trup",
    "glop",
    "slop",
    "snop",
    "gnum",
    "gnun",
    "gnup",
    "gnump",
    "grum",
    "gonk",
    "blart",
    "shart",
    "zoop",
    "zorp",
    "boof",
    "gank",
    "spung",
    "bung",
    "grib",
    "plunk",
    "guff",
    "chuff",
    "wank",
    "muck",
    "gleb",
    "gulg",
    "splat",
    "tonk",
    "filk",
    "slud",
    "dolk",
    "bunk",
    "shon",
    "gron",
    "blon",
    "gnon",
    "tron",
    "mung",
    "thorp"
  ]
};
